import { Dataset } from '../router/types';

export const createDataset: () => Dataset = () => ({
  clients: [
    {
      id: 0,
      client_id: 'client_JnVvPWxBz4Ep7YcpJFeU',
      client_secret: '7dn2cmvUS5btm1S6Mfygd7vaVBuv7Cf8Fx1HKqsx',
      redirect_uri: 'https://admin.acme.test',
      javascript_origin_uri: '',
      project_name: 'Foxy Widgets for Acme Admin',
      project_description: 'View your recent transactions from Foxy right in the Acme Admin.',
      company_name: 'Acme Inc.',
      company_url: 'https://acme.test',
      company_logo: 'https://picsum.photos/64',
      contact_name: 'Sally Sims',
      contact_email: 'sally.sims@example.com',
      contact_phone: '555-555-5555',
    },
    {
      id: 1,
      client_id: 'client_ApVvPWxBz4ap7YcpJoe1',
      client_secret: 'lln2cmvasdbtm1S6Mfygd7vaVBuv23f8Fx1HKqs2',
      redirect_uri: 'https://admin.acme.test',
      javascript_origin_uri: '',
      project_name: '',
      project_description: '',
      company_name: '',
      company_url: '',
      company_logo: '',
      contact_name: '',
      contact_email: '',
      contact_phone: '',
    },
  ],

  passkeys: [
    {
      id: 0,
      user_id: 0,
      credential_id: 'EVAfAKj33924v0A3V4RQ-RVew4r4WEFDL',
      user_name: 'sally.sims@example.com',
      last_login_date: '2023-02-21T12:20:10-0700',
      last_login_ua:
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15',
      date_created: '2023-02-21T12:20:10-0700',
      date_modified: null,
    },
    {
      id: 1,
      user_id: 0,
      credential_id: 'EVAfAKj33924v0A3V4RQ-RVew4r4WEFDL',
      user_name: 'sally.sims@example.com',
      last_login_date: null,
      last_login_ua: null,
      date_created: null,
      date_modified: null,
    },
  ],

  downloadables: [
    {
      id: 0,
      store_id: 0,
      item_category_id: 0,
      item_category_uri: 'https://demo.api/hapi/item_categories/0',
      name: '1 Year Workout Plan',
      code: '1YRWT',
      price: 25,
      file_name: '1_year_workout.pdf',
      file_size: 32 * 1024 * 1024,
      upload_date: '2023-02-21T12:20:10-0700',
      date_created: '2023-02-21T12:20:10-0700',
      date_modified: '2023-02-21T12:20:10-0700',
    },
  ],

  applied_taxes: [
    {
      id: 0,
      tax_id: 0,
      store_id: 0,
      transaction_id: 0,
      rate: 8.0,
      name: 'US Sales Tax',
      amount: 1.7765,
      apply_to_handling: true,
      apply_to_shipping: true,
      is_future_tax: false,
      shipto: '',
      date_created: '2021-03-29T13:57:40-0700',
      date_modified: '2021-03-29T13:57:40-0700',
    },
  ],

  discounts: [
    {
      id: 0,
      cart_id: 0,
      store_id: 0,
      coupon_id: 0,
      customer_id: 0,
      coupon_code_id: 0,
      transaction_id: 0,
      code: '1WLCM',
      amount: -1,
      name: 'Welcome Bonus',
      display: '-1.00',
      is_taxable: false,
      is_future_discount: false,
      date_created: '2021-03-29T13:57:40-0700',
      date_modified: '2021-03-29T13:57:40-0700',
    },
  ],

  payments: [
    {
      id: 0,
      store_id: 0,
      transaction_id: 0,
      type: 'plastic',
      gateway_type: 'authorize',
      processor_response: 'Authorize.net Transaction ID: 2233990980',
      processor_response_details: '',
      purchase_order: '',
      cc_number_masked: 'xxxxxxxxxxxx1111',
      cc_type: 'Visa',
      cc_exp_month: '01',
      cc_exp_year: '2017',
      fraud_protection_score: 0,
      paypal_payer_id: '',
      third_party_id: '',
      amount: 20.15,
      date_created: '2015-05-21T14:22:09-0700',
      date_modified: '2015-05-21T14:22:09-0700',
    },
  ],

  error_entries: [
    {
      id: 0,
      store_id: 0,
      transaction_id: 0,
      url: 'https://serverless.foxycartdev.com/checkout',
      error_message: 'DataFeed Failed: (2) 2012-08-10 12:12:49 No data returned',
      user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6)',
      referrer: 'https://serverless.foxycart.test/checkout',
      ip_address: '10.0.0.1',
      ip_country: 'United States',
      post_values: '',
      get_values: '',
      hide_error: false,
      date_created: '2021-03-29T13:57:40-0700',
      date_modified: '2021-03-29T13:57:40-0700',
    },
  ],

  custom_fields: [
    {
      id: 0,
      cart_id: 0,
      store_id: 0,
      transaction_id: 0,
      name: 'Terms & Conditions',
      value: 'Checked',
      is_hidden: true,
      date_created: '2013-08-05T14:15:59-0700',
      date_modified: '2013-08-05T14:15:59-0700',
    },
  ],

  store_attributes: [
    {
      id: 0,
      name: 'foxy-admin-bookmark',
      value:
        '/stores/0/transactions?filter_name=Red%20%26%20Heavy&amp;filter_query=color%3Dred%26weight%3Agreaterthan%3D4',
      store_id: 0,
      visibility: 'private',
      date_created: '2013-08-05T14:15:59-0700',
      date_modified: '2013-08-05T14:15:59-0700',
    },
  ],

  customer_attributes: [
    {
      id: 0,
      name: 'Hours',
      value: '9am to 5pm',
      customer_id: 0,
      visibility: 'private',
      date_created: '2013-08-05T14:15:59-0700',
      date_modified: '2013-08-05T14:15:59-0700',
    },
  ],

  cart_attributes: [
    {
      id: 0,
      name: 'Internal ID',
      value: 'CT-123',
      cart_id: 0,
      visibility: 'private',
      date_created: '2013-08-05T14:15:59-0700',
      date_modified: '2013-08-05T14:15:59-0700',
    },
  ],

  item_attributes: [
    {
      id: 0,
      name: 'Color',
      value: 'Red',
      item_id: 0,
      visibility: 'private',
      date_created: '2013-08-05T14:15:59-0700',
      date_modified: '2013-08-05T14:15:59-0700',
    },
  ],

  shipment_attributes: [
    {
      id: 0,
      name: 'Color',
      value: 'Red',
      item_id: 0,
      visibility: 'private',
      date_created: '2013-08-05T14:15:59-0700',
      date_modified: '2013-08-05T14:15:59-0700',
    },
  ],

  item_options: [
    {
      id: 0,
      item_id: 0,
      store_id: 0,
      transaction_id: 0,
      name: 'Color',
      value: 'Blue',
      price_mod: 11.98,
      weight_mod: 0,
      date_created: '2012-02-29T13:55:09-0800',
      date_modified: '2012-02-29T13:55:09-0800',
    },
    {
      id: 1,
      item_id: 0,
      store_id: 0,
      transaction_id: 0,
      name: 'Box & Ribbon',
      value: 'No',
      price_mod: -1.99,
      weight_mod: -2,
      date_created: '2012-02-29T13:55:09-0800',
      date_modified: '2012-02-29T13:55:09-0800',
    },
    {
      id: 2,
      item_id: 0,
      store_id: 0,
      transaction_id: 0,
      name: 'Message',
      value: 'None',
      price_mod: 0,
      weight_mod: 0,
      date_created: '2012-02-29T13:55:09-0800',
      date_modified: '2012-02-29T13:55:09-0800',
    },
  ],

  customer_addresses: [
    {
      id: 0,
      store_id: 0,
      customer_id: 0,
      address_name: 'Example address',
      first_name: 'Sarah',
      last_name: 'Jane',
      company: 'My company',
      address1: '12345 Any Street',
      address2: '',
      city: 'Any City',
      region: 'TN',
      postal_code: '37211',
      country: 'US',
      phone: '',
      is_default_billing: true,
      is_default_shipping: false,
      ignore_address_restrictions: false,
      date_created: '2013-08-16T14:53:46-0700',
      date_modified: '2013-08-16T14:53:46-0700',
    },
    {
      id: 1,
      store_id: 0,
      customer_id: 0,
      address_name: 'Example address',
      first_name: 'Sarah',
      last_name: 'Jane',
      company: 'My company',
      address1: '12345 Any Street',
      address2: '',
      city: 'Any City',
      region: 'TN',
      postal_code: '37211',
      country: 'US',
      phone: '',
      is_default_billing: false,
      is_default_shipping: true,
      ignore_address_restrictions: false,
      date_created: '2013-08-16T14:53:46-0700',
      date_modified: '2013-08-16T14:53:46-0700',
    },
    {
      id: 2,
      store_id: 0,
      customer_id: 0,
      address_name: 'Example address',
      first_name: 'Sarah',
      last_name: 'Jane',
      company: 'My company',
      address1: '12345 Any Street',
      address2: '',
      city: 'Any City',
      region: 'TN',
      postal_code: '37211',
      country: 'US',
      phone: '',
      is_default_billing: false,
      is_default_shipping: false,
      ignore_address_restrictions: false,
      date_created: '2013-08-16T14:53:46-0700',
      date_modified: '2013-08-16T14:53:46-0700',
    },
    {
      id: 3,
      store_id: 0,
      customer_id: 0,
      address_name: 'Example address',
      first_name: 'Sarah',
      last_name: 'Jane',
      company: 'My company',
      address1: '12345 Any Street',
      address2: '',
      city: 'Any City',
      region: 'TN',
      postal_code: '37211',
      country: 'US',
      phone: '',
      is_default_billing: false,
      is_default_shipping: false,
      ignore_address_restrictions: false,
      date_created: '2013-08-16T14:53:46-0700',
      date_modified: '2013-08-16T14:53:46-0700',
    },
  ],

  email_templates: [
    {
      id: 0,
      store_id: 0,
      description: 'Email Receipt Template',
      subject: '{{ store_name }} Order ({{ order_id }})',
      content_html:
        '<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <title>Document</title>\n  </head>\n  <body>\n    Test Markup\n  </body>\n</html>',
      content_html_url: 'https://example.com/template.html',
      content_text: 'Test Text',
      content_text_url: 'https://example.com/text_template.txt',
      date_created: '2012-08-10T11:58:54-0700',
      date_modified: '2012-08-10T11:58:54-0700',
    },
  ],

  payment_methods: [
    {
      id: 0,
      store_id: 0,
      customer_id: 0,
      save_cc: true,
      cc_type: 'MasterCard',
      cc_number_masked: 'xxxxxxxxxxxx1111',
      cc_exp_month: '12',
      cc_exp_year: '2020',
      date_created: '2009-02-10T21:41:51-0800',
      date_modified: '2013-08-17T17:40:22-0700',
    },
    {
      id: 1,
      store_id: 0,
      customer_id: 0,
      save_cc: false,
      cc_type: '',
      cc_number_masked: '',
      cc_exp_month: '',
      cc_exp_year: '',
      date_created: '2009-02-10T21:41:51-0800',
      date_modified: '2013-08-17T17:40:22-0700',
    },
  ],

  subscriptions: [
    {
      id: 0,
      store_id: 0,
      customer_id: 0,
      last_transaction_id: 0,
      transaction_template_id: 0,
      next_transaction_date: '2021-06-19T10:58:39-0700',
      start_date: '2023-02-11T22:45:01-0700',
      end_date: null,
      frequency: '1m',
      error_message: '',
      past_due_amount: 0,
      first_failed_transaction_date: null,
      is_active: true,
      third_party_id: '',
      date_created: '2020-08-19T10:58:39-0700',
      date_modified: '2020-08-19T10:58:39-0700',
    },
  ],

  transactions: [
    {
      id: 0,
      store_id: 0,
      customer_id: 0,
      subscription_id: 0,
      is_test: true,
      display_id: 2134962574,
      is_editable: true,
      hide_transaction: false,
      data_is_fed: true,
      transaction_date: '2013-06-06T17:26:07-05:00',
      locale_code: 'en_US',
      customer_first_name: 'Test',
      customer_last_name: 'User',
      customer_tax_id: '',
      customer_email: 'testing@example.com',
      customer_ip: '93.31.81.25',
      ip_country: 'France',
      user_agent:
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Safari/605.1.15',
      total_item_price: 10,
      total_tax: 1.9,
      total_shipping: 0,
      total_future_shipping: 0,
      total_order: 11.9,
      date_created: '2013-06-06T15:26:07-0700',
      date_modified: '2013-06-06T15:26:07-0700',
      currency_code: 'USD',
      currency_symbol: '$',
      status: 'completed',
      source: 'cit_ecommerce',
      type: '',
    },
    {
      id: 1,
      store_id: 0,
      customer_id: 0,
      subscription_id: 0,
      is_test: true,
      is_editable: false,
      hide_transaction: false,
      data_is_fed: true,
      transaction_date: '2021-06-06T17:26:07-05:00',
      locale_code: 'en_US',
      customer_first_name: 'Test',
      customer_last_name: 'User',
      customer_tax_id: '',
      customer_email: 'testing@example.com',
      customer_ip: '10.1.248.210',
      ip_country: '',
      total_item_price: 20,
      total_tax: 1.9,
      total_shipping: 0,
      total_future_shipping: 0,
      total_order: 21.9,
      date_created: '2021-06-06T15:26:07-0700',
      date_modified: '2021-06-06T15:26:07-0700',
      currency_code: 'EUR',
      currency_symbol: '€',
      status: 'approved',
    },
  ],

  customers: [
    {
      id: 0,
      store_id: 0,
      tax_id: 'XXX-XX-XXXX',
      payment_method_id: 0,
      last_login_date: '2013-08-16T14:13:54-0700',
      first_name: 'Sally',
      last_name: 'Sims',
      email: 'sally.sims@example.com',
      password_salt: null,
      password_hash: '4443fe50df6b177ba84b78dd91f0958a',
      password_hash_type: 'md5',
      password_hash_config: null,
      forgot_password: '1234567890',
      forgot_password_timestamp: '2013-08-16T14:13:54-0700',
      is_anonymous: false,
      date_created: '2013-08-16T14:13:54-0700',
      date_modified: '2013-08-16T14:13:54-0700',
    },
    {
      id: 1,
      store_id: 0,
      tax_id: 'XXX-XX-XXXX',
      payment_method_id: 0,
      last_login_date: '2013-08-16T14:13:54-0700',
      first_name: 'Jim',
      last_name: 'Tucker',
      email: 'jim.tucker@example.com',
      password_salt: null,
      password_hash: '4443fe50df6b177ba84b78dd91f0958a',
      password_hash_type: 'md5',
      password_hash_config: null,
      forgot_password: 'blah',
      forgot_password_timestamp: '2013-08-16T14:13:54-0700',
      is_anonymous: false,
      date_created: '2013-08-16T14:13:54-0700',
      date_modified: '2013-08-16T14:13:54-0700',
    },
    {
      id: 2,
      store_id: 0,
      tax_id: 'XXX-XX-XXXX',
      payment_method_id: 0,
      last_login_date: '2013-08-16T14:13:54-0700',
      first_name: 'George',
      last_name: 'Cole',
      email: 'george.cole@example.com',
      password_salt: null,
      password_hash: '4443fe50df6b177ba84b78dd91f0958a',
      password_hash_type: 'md5',
      password_hash_config: null,
      forgot_password: 'blah',
      forgot_password_timestamp: '2013-08-16T14:13:54-0700',
      is_anonymous: false,
      date_created: '2013-08-16T14:13:54-0700',
      date_modified: '2013-08-16T14:13:54-0700',
    },
    {
      id: 3,
      store_id: 0,
      tax_id: 'XXX-XX-XXXX',
      last_login_date: '2013-08-16T14:13:54-0700',
      first_name: 'Nora',
      last_name: 'Payne',
      email: 'nora.payne@example.com',
      password_salt: null,
      password_hash: '4443fe50df6b177ba84b78dd91f0958a',
      password_hash_type: 'md5',
      password_hash_config: null,
      forgot_password: 'blah',
      forgot_password_timestamp: '2013-08-16T14:13:54-0700',
      is_anonymous: false,
      date_created: '2013-08-16T14:13:54-0700',
      date_modified: '2013-08-16T14:13:54-0700',
    },
    {
      id: 4,
      store_id: 0,
      tax_id: 'XXX-XX-XXXX',
      last_login_date: '2013-08-16T14:13:54-0700',
      first_name: 'Rafael',
      last_name: 'Reyes',
      email: 'rafael.reyes@example.com',
      password_salt: null,
      password_hash: '4443fe50df6b177ba84b78dd91f0958a',
      password_hash_type: 'md5',
      password_hash_config: null,
      forgot_password: 'blah',
      forgot_password_timestamp: '2013-08-16T14:13:54-0700',
      is_anonymous: false,
      date_created: '2013-08-16T14:13:54-0700',
      date_modified: '2013-08-16T14:13:54-0700',
    },
  ],

  stores: [
    {
      id: 0,
      store_version_uri: 'https://demo.api/hapi/store_versions/1',
      store_name: 'Acme Corporation',
      store_domain: 'acme',
      use_remote_domain: false,
      store_url: 'https://example.com/',
      receipt_continue_url: '',
      store_email: 'example@example.com',
      from_email: 'john.doe@example.com',
      use_email_dns: false,
      bcc_on_receipt_email: true,
      smtp_config: '',
      postal_code: '37211',
      region: 'TN',
      country: 'US',
      locale_code: 'en_US',
      timezone: 'America/Los_Angeles',
      hide_currency_symbol: false,
      hide_decimal_characters: false,
      use_international_currency_symbol: true,
      language: 'english',
      logo_url: 'https://picsum.photos/64',
      checkout_type: 'default_account',
      use_webhook: false,
      webhook_url: '',
      webhook_key: '',
      use_cart_validation: false,
      use_single_sign_on: false,
      single_sign_on_url: '',
      customer_password_hash_type: 'phpass',
      customer_password_hash_config: 8,
      features_multiship: false,
      products_require_expires_property: false,
      app_session_time: 0,
      shipping_address_type: 'residential',
      require_signed_shipping_rates: false,
      unified_order_entry_password: '',
      custom_display_id_config: '',
      affiliate_id: 0,
      is_maintenance_mode: false,
      is_active: false,
      first_payment_date: '2016-02-05T10:25:26-0800',
      date_created: '2016-02-05T10:25:26-0800',
      date_modified: '2016-02-05T10:25:26-0800',
    },
  ],

  items: new Array(20).fill(0).map((_, id) => ({
    id,
    cart_id: 0,
    store_id: 0,
    shipment_id: id > 4 ? 1 : 0,
    transaction_id: id > 4 ? 1 : 0,
    subscription_id: 0,
    item_category_id: 0,
    item_category_uri: `https://demo.api/hapi/item_categories/${id}`,
    name: `Basic Product #${id}`,
    price: 10,
    quantity: Math.ceil(Math.random() * 10),
    quantity_min: 0,
    quantity_max: 0,
    weight: 5,
    code: `PDCT0${id}`,
    parent_code: '',
    discount_name: '',
    discount_type: '',
    discount_details: '',
    subscription_frequency: '1m',
    subscription_start_date: '2015-04-15',
    subscription_next_transaction_date: '2022-05-12',
    subscription_end_date: null,
    is_future_line_item: false,
    shipto: 'Me',
    url: '',
    image: 'https://picsum.photos/320',
    length: 0,
    width: 0,
    height: 0,
    expires: 0,
    date_created: '2015-04-15T08:45:49-0700',
    date_modified: '2015-04-15T08:45:49-0700',
  })),

  carts: [
    {
      id: 0,
      store_id: 0,
      customer_id: 0,
      template_set_id: 0,
      customer_uri: 'https://demo.api/hapi/customers/0',
      customer_email: 'sally.sims@example.com',
      template_set_uri: 'https://demo.api/hapi/template_sets/0',
      language: 'english',
      use_customer_shipping_address: true,
      billing_first_name: 'Grace',
      billing_last_name: 'Hopper',
      billing_company: '',
      billing_address1: '1234 Mulberry Dr.',
      billing_address2: '#567',
      billing_city: 'MANHATTAN',
      billing_state: 'NY',
      billing_postal_code: '10001',
      billing_country: 'US',
      billing_phone: '',
      shipping_first_name: 'test1',
      shipping_last_name: 'test2',
      shipping_company: 'test3',
      shipping_address1: 'test4',
      shipping_address2: 'test5',
      shipping_city: 'Austin',
      shipping_state: 'TX',
      shipping_postal_code: '78767',
      shipping_country: 'US',
      shipping_phone: '',
      total_item_price: 123.45,
      total_tax: 12.3,
      total_shipping: 4.5,
      total_future_shipping: 0,
      total_order: 158.99,
      currency_code: 'USD',
      date_created: '2012-02-29T13:55:09-0800',
      date_modified: '2012-02-29T13:55:09-0800',
    },
  ],

  cart_templates: [
    {
      id: 0,
      store_id: 0,
      description: 'Cart Template',
      content: `<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <title>Document</title>\n  </head>\n  <body>\n    Test Markup\n  </body>\n</html>`,
      content_url: 'http://example.com/cart-template',
      date_created: '2012-08-10T11:58:54-0700',
      date_modified: '2012-08-10T11:58:54-0700',
    },
  ],

  customer_portal_settings: [
    {
      id: 0,
      store_id: 0,
      sessionLifespanInMinutes: 90,
      allowedOrigins: ['https://themancan.com'],
      subscriptions: {
        allowFrequencyModification: [
          {
            jsonataQuery: '$contains(frequency, "m")',
            values: ['.5m', '1m', '2m'],
          },
          {
            jsonataQuery: '$contains(frequency, "y")',
            values: ['1y', '2y'],
          },
        ],
        allowNextDateModification: [
          {
            allowedDays: {
              days: [1, 3, 5],
              type: 'day',
            },
            disallowedDates: ['2021-09-02', '2021-09-03', '2021-09-01'],
            jsonataQuery: '$contains(frequency, "m")',
            max: '2y',
            min: '1w',
          },
        ],
      },
      sso: true,
      date_created: '2020-04-13T08:44:09-0700',
      date_modified: '2020-04-13T08:46:03-0700',
    },
  ],

  taxes: [
    {
      id: 0,
      store_id: 0,
      name: 'Beverage tax',
      type: 'region',
      country: 'US',
      region: 'TN',
      city: '',
      is_live: true,
      service_provider: 'avalara',
      apply_to_shipping: true,
      use_origin_rates: true,
      exempt_all_customer_tax_ids: true,
      rate: 1,
      date_created: '2013-08-19T10:58:39-0700',
      date_modified: '2013-08-19T10:58:39-0700',
    },
    {
      id: 1,
      store_id: 0,
      name: 'Sample tax',
      type: 'region',
      country: 'US',
      region: 'TN',
      city: '',
      is_live: true,
      service_provider: 'avalara',
      apply_to_shipping: true,
      use_origin_rates: true,
      exempt_all_customer_tax_ids: true,
      rate: 1,
      date_created: '2013-08-19T10:58:39-0700',
      date_modified: '2013-08-19T10:58:39-0700',
    },
  ],

  tax_item_categories: [],

  users: [
    {
      id: 0,
      store_id: 0,
      first_name: 'Ann',
      last_name: 'Doe',
      email: 'ann.doe@example.com',
      phone: '444-444-4444',
      affiliate_id: 0,
      is_programmer: true,
      is_front_end_developer: false,
      is_designer: false,
      is_merchant: true,
      date_created: '2007-05-23T16:09:12-0700',
      date_modified: '2013-07-10T22:37:49-0700',
    },
  ],

  template_configs: [
    {
      id: 0,
      store_id: 0,
      description: 'Template Config',
      json: '{"cart_type":"default","checkout_type":"default_account","csc_requirements":"all_cards","tos_checkbox_settings":{"usage":"none","initial_state":"unchecked","is_hidden":false,"url":""},"eu_secure_data_transfer_consent":{"usage":"required"},"newsletter_subscribe":{"usage":"none"},"analytics_config":{"usage":"none","google_analytics":{"usage":"none","account_id":"","include_on_site":false},"google_tag":{"usage":"none","send_to":""}},"colors":{"usage":"none","primary":"4D4D4D","secondary":"FFFFFF","tertiary":"FFFFFF"},"use_checkout_confirmation_window":{"usage":"none"},"supported_payment_cards":["visa","mastercard","discover","amex"],"custom_checkout_field_requirements":{"cart_controls":"enabled","coupon_entry":"enabled","billing_first_name":"required","billing_last_name":"required","billing_company":"optional","billing_tax_id":"hidden","billing_phone":"optional","billing_address1":"required","billing_address2":"optional","billing_city":"required","billing_region":"default","billing_postal_code":"required","billing_country":"required"},"cart_display_config":{"usage":"required","show_product_weight":false,"show_product_category":true,"show_product_code":true,"show_product_options":true,"show_sub_frequency":true,"show_sub_startdate":true,"show_sub_nextdate":true,"show_sub_enddate":true,"hidden_product_options":["my_option"]},"foxycomplete":{"usage":"required","show_combobox":true,"combobox_open":"\\u25bc","combobox_close":"\\u25b2","show_flags":true},"custom_script_values":{"header":"","footer":"","checkout_fields":"","multiship_checkout_fields":""},"http_receipt":false,"custom_config":{},"debug":{"usage":"none"},"location_filtering":{"usage":"both","shipping_filter_type":"blacklist","billing_filter_type":"blacklist","shipping_filter_values":{"CA":["ON","AB","QB"]},"billing_filter_values":{"CA":["ON","AB","QB"]}},"postal_code_lookup":{"usage":"enabled"}}',
      date_created: '2012-08-10T11:58:54-0700',
      date_modified: '2012-08-10T11:58:54-0700',
    },
  ],

  coupons: new Array(12).fill(0).map((_, id) => ({
    id,
    store_id: 0,
    name: `October Sale ${id}`,
    start_date: '2020-03-29T13:57:40-0700',
    end_date: null,
    number_of_uses_allowed: 100,
    number_of_uses_to_date: 31,
    number_of_uses_allowed_per_code: 0,
    coupon_discount_type: 'quantity_percentage',
    coupon_discount_details: 'repeat|6-10',
    customer_auto_apply: false,
    customer_attribute_restrictions: '',
    customer_subscription_restrictions: '',
    combinable: true,
    multiple_codes_allowed: true,
    product_code_restrictions: 'abc123,fun_*,*_small,-foobar,-*_example,-test_code',
    exclude_category_discounts: false,
    exclude_line_item_discounts: false,
    is_taxable: true,
    date_created: '2014-04-21T13:40:45-0700',
    date_modified: '2015-03-16T12:30:58-0700',
  })),

  coupon_codes: new Array(100).fill(0).map((_, id) => ({
    id,
    store_id: 0,
    coupon_id: 0,
    code: `OCTBRSL22${id}`,
    number_of_uses_to_date: Math.floor(Math.random() * 100),
    date_created: '2014-04-21T13:40:45-0700',
    date_modified: '2022-02-16T12:30:58-0700',
  })),

  generate_codes: [
    {
      id: 0,
      message: 'All codes added successfully.',
    },
  ],

  item_categories: new Array(12).fill(0).map((_, id) => ({
    id: id,
    store_id: 0,
    admin_email_template_uri: '',
    customer_email_template_uri: '',
    code: `CATEGORY_${id}`,
    name: `Test Category ${id}`,
    item_delivery_type: 'notshipped',
    max_downloads_per_customer: 3,
    max_downloads_time_period: 24,
    customs_value: 0,
    default_weight: 1,
    default_weight_unit: 'LBS',
    default_length_unit: 'IN',
    shipping_flat_rate: 0,
    shipping_flat_rate_type: 'per_order',
    handling_fee: 0,
    handling_fee_minimum: 0,
    handling_fee_type: 'none',
    handling_fee_percentage: 0,
    discount_name: null,
    discount_type: null,
    discount_details: null,
    send_customer_email: false,
    send_admin_email: false,
    admin_email: null,
    date_created: '2012-10-31T14:12:39-0700',
    date_modified: '2012-10-31T14:12:39-0700',
  })),

  coupon_attributes: [],

  coupon_item_categories: [
    {
      id: 0,
      coupon_id: 0,
      item_category_id: 0,
      coupon_uri: 'https://demo.api/hapi/coupons/0',
      item_category_uri: 'https://demo.api/hapi/item_categories/0',
      date_created: '2012-10-31T14:12:39-0700',
      date_modified: '2012-10-31T14:12:39-0700',
    },
  ],

  gift_cards: [
    {
      id: 0,
      store_id: 0,
      name: 'Silver Gift Card (US)',
      currency_code: 'USD',
      expires_after: '5y',
      product_code_restrictions: 'abc123,fun_*,*_small,-foobar,-*_example,-test_code',
      date_created: '2014-04-21T13:40:45-0700',
      date_modified: '2015-03-16T12:30:58-0700',
    },
  ],

  gift_card_attributes: [],

  gift_card_codes: new Array(100).fill(0).map((_, id) => ({
    id,
    store_id: 0,
    gift_card_id: 0,
    code: `GIFTCARD${id}`,
    end_date: Math.random() > 0.5 ? '2022-02-16T12:30:58-0700' : null,
    current_balance: Math.round(Math.random() * 100),
    date_created: '2014-04-21T13:40:45-0700',
    date_modified: '2022-02-16T12:30:58-0700',
    ...(id % 2 === 0 ? { item_id: 0 } : null),
  })),

  gift_card_code_logs: [
    {
      id: 0,
      store_id: 0,
      gift_card_id: 0,
      gift_card_code_id: 0,
      transaction_id: 0,
      external_id: null,
      balance_adjustment: -40.3,
      user_id: null,
      source: null,
      date_created: '2021-11-15T19:30:33-0800',
      date_modified: '2021-11-15T19:30:35-0800',
    },
    {
      id: 1,
      store_id: 0,
      gift_card_id: 0,
      gift_card_code_id: 0,
      transaction_id: null,
      external_id: null,
      balance_adjustment: 20,
      user_id: 0,
      source: null,
      date_created: '2021-10-08T12:30:33-0800',
      date_modified: '2021-10-08T12:30:35-0800',
    },
  ],

  applied_gift_card_codes: [
    {
      id: 0,
      store_id: 0,
      gift_card_id: 0,
      gift_card_code_id: 0,
      transaction_id: 0,
      external_id: null,
      balance_adjustment: -40.3,
      user_id: null,
      source: null,
      date_created: '2021-11-15T19:30:33-0800',
      date_modified: '2021-11-15T19:30:35-0800',
    },
    {
      id: 1,
      store_id: 0,
      gift_card_id: 0,
      gift_card_code_id: 0,
      transaction_id: null,
      external_id: null,
      balance_adjustment: 20,
      user_id: 0,
      source: null,
      date_created: '2021-10-08T12:30:33-0800',
      date_modified: '2021-10-08T12:30:35-0800',
    },
  ],

  gift_card_item_categories: [],

  reports: [
    {
      id: 0,
      user_id: 0,
      store_id: 0,
      name: 'customers',
      version: '1',
      datetime_start: '2022-01-01T00:00:00-0800',
      datetime_end: '2022-12-31T00:00:00-0800',
      status: 'ready',
      date_created: '2022-01-01T00:00:00-0800',
      date_modified: '2022-01-01T00:00:00-0800',
    },
    {
      id: 1,
      user_id: 0,
      store_id: 0,
      name: 'customers_ltv',
      version: '1',
      datetime_start: '2022-01-01T00:00:00-0800',
      datetime_end: '2022-12-31T00:00:00-0800',
      status: 'error',
      date_created: '2022-01-01T00:00:00-0800',
      date_modified: '2022-01-01T00:00:00-0800',
    },
    {
      id: 2,
      user_id: 0,
      store_id: 0,
      name: 'complete',
      version: '1',
      datetime_start: '2022-01-01T00:00:00-0800',
      datetime_end: '2022-12-31T00:00:00-0800',
      status: 'queued',
      date_created: '2022-01-01T00:00:00-0800',
      date_modified: '2022-01-01T00:00:00-0800',
    },
  ],

  discount_details: new Array(3).fill(0).map((_, id) => ({
    id,
    item_id: 0,
    store_id: 0,
    transaction_id: 0,
    name: `Product Level Discount #${id}`,
    amount_per: 0 - Math.random() * 10,
    date_created: '2022-01-01T00:00:00-0800',
    date_modified: '2022-01-01T00:00:00-0800',
  })),

  coupon_details: new Array(3).fill(0).map((_, id) => ({
    id,
    item_id: 0,
    store_id: 0,
    coupon_id: 0,
    coupon_code_id: 0,
    transaction_id: 0,
    name: 'October Sale',
    code: `OCTBRSL${id}`,
    amount_per: 0 - Math.random() * 10,
    date_created: '2022-01-01T00:00:00-0800',
    date_modified: '2022-01-01T00:00:00-0800',
  })),

  shipments: [
    {
      id: 0,
      store_id: 0,
      transaction_id: 0,
      customer_id: 0,
      customer_address_id: 0,
      address_name: 'Default Shipping Address',
      first_name: 'John',
      last_name: 'Doe',
      company: '',
      address1: '1234 Anystreet',
      address2: '',
      city: 'NASHVILLE',
      region: 'TN',
      postal_code: '37211',
      country: 'US',
      phone: '555-555-55555',
      shipping_service_id: 55,
      shipping_service_description: 'FedEx Home Delivery',
      total_item_price: 10,
      total_tax: 1.99,
      total_shipping: 11.29,
      total_price: 23.28,
      date_created: '2015-04-15T08:46:39-0700',
      date_modified: '2015-04-15T08:46:39-0700',
    },
    {
      id: 1,
      store_id: 0,
      transaction_id: 1,
      customer_id: 0,
      customer_address_id: 0,
      address_name: 'Default Shipping Address',
      first_name: 'John',
      last_name: 'Doe',
      company: '',
      address1: '1234 Anystreet',
      address2: '',
      city: 'NASHVILLE',
      region: 'TN',
      postal_code: '37211',
      country: 'US',
      phone: '555-555-55555',
      shipping_service_id: 55,
      shipping_service_description: 'FedEx Home Delivery',
      total_item_price: 10,
      total_tax: 1.99,
      total_shipping: 11.29,
      total_price: 23.28,
      date_created: '2015-04-15T08:46:39-0700',
      date_modified: '2015-04-15T08:46:39-0700',
    },
  ],

  webhooks: [
    {
      id: 0,
      store_id: 0,
      format: 'json',
      version: 2,
      name: 'My JSON endpoint',
      url: 'https://example.com',
      query: 'zoom=items',
      encryption_key: 'HNL978XVXXCM66DM5N2T78D5MT66BC6D',
      event_resource: 'transaction',
      date_created: '2020-10-28T07:03:19-0700',
      date_modified: '2020-10-28T08:45:46-0700',
    },
  ],

  webhook_statuses: [
    {
      id: 0,
      store_id: 0,
      webhook_id: 0,
      resource_id: 0,
      resource_type: 'transaction',
      status: 'pending',
      date_created: '2020-10-28T07:03:19-0700',
      date_modified: '2020-10-28T08:45:46-0700',
    },
  ],

  webhook_logs: [
    {
      id: 0,
      store_id: 0,
      webhook_id: 0,
      resource_id: 0,
      resource_type: 'transaction',
      response_body: JSON.stringify({ status: 'OK', timestamp: Date.now() }),
      response_code: '200',
      date_created: '2020-10-28T07:03:19-0700',
      date_modified: '2020-10-28T08:45:46-0700',
    },
  ],

  store_shipping_methods: [
    {
      id: 0,
      store_id: 0,
      shipping_method_id: 0,
      shipping_container_id: 0,
      shipping_drop_type_id: 0,
      shipping_method_uri: 'https://demo.api/hapi/shipping_methods/0',
      shipping_container_uri: 'https://demo.api/hapi/shipping_containers/0',
      shipping_drop_type_uri: 'https://demo.api/hapi/shipping_drop_types/0',
      accountid: 'my-account-123',
      password: 'super-secret-password',
      meter_number: '',
      authentication_key: '',
      use_for_domestic: true,
      use_for_international: false,
      date_created: '2020-10-28T07:03:19-0700',
      date_modified: '2020-10-28T08:45:46-0700',
    },
    {
      id: 1,
      store_id: 0,
      shipping_method_id: 1,
      shipping_method_uri: 'https://demo.api/hapi/shipping_methods/1',
      use_for_domestic: true,
      use_for_international: true,
      deployment_status: 'deployed',
      custom_code:
        "rates.add(10002, 5, '', 'Ground Custom 2002');\r\nrates.add(10012, 50, '', 'Expensive');\r\n\r\nif (!rates.exists()) {\r\n\trates.add(10001, 15, '', 'Fallback Shipping');\r\n}",
      date_created: '2020-10-28T07:03:19-0700',
      date_modified: '2020-10-28T08:45:46-0700',
    },
  ],

  store_shipping_services: [
    {
      id: 0,
      store_id: 0,
      shipping_method_id: 0,
      shipping_service_id: 0,
      shipping_method_uri: 'https://demo.api/hapi/shipping_methods/0',
      shipping_service_uri: 'https://demo.api/hapi/shipping_services/0',
      date_created: '2020-10-28T07:03:19-0700',
      date_modified: '2020-10-28T08:45:46-0700',
    },
  ],

  shipping_methods: [
    {
      id: 0,
      name: 'United States Postal Service',
      code: 'USPS',
      date_created: null,
      date_modified: null,
    },
    {
      id: 1,
      name: 'Custom Shipping Code',
      code: 'CUSTOM-CODE',
      date_created: null,
      date_modified: null,
    },
  ],

  shipping_containers: [
    {
      id: 0,
      shipping_method_id: 0,
      name: 'Regular Size',
      code: 'VARIABLE',
      date_created: null,
      date_modified: null,
    },
  ],

  shipping_drop_types: [
    {
      id: 0,
      shipping_method_id: 0,
      name: 'Regular Pickup',
      code: 'REGULARPICKUP',
      date_created: null,
      date_modified: null,
    },
  ],

  shipping_services: [
    {
      id: 0,
      shipping_method_id: 0,
      name: 'Priority Mail',
      code: '1',
      is_international: true,
      date_created: null,
      date_modified: null,
    },
  ],

  payment_gateways: [
    {
      id: 0,
      store_id: 0,
      description: 'Default payment gateway',
      type: 'authorize',
      use_auth_only: false,
      account_id: '',
      account_key: '',
      third_party_key: '',
      config_3d_secure: '',
      additional_fields: '',
      test_account_id: 'BxFSnPy7',
      test_account_key: '8SPBTpqs4uf2ZwM8',
      test_third_party_key: '',
      date_created: '2014-07-17T06:46:00-0700',
      date_modified: '2014-07-17T06:46:00-0700',
    },
  ],

  hosted_payment_gateways: [
    {
      id: 0,
      store_id: 0,
      payment_method_set_id: 0,
      description: 'Default hosted payment gateway',
      type: 'amazon_mws',
      use_auth_only: false,
      account_id: '',
      account_key: '',
      third_party_key: '',
      config_3d_secure: '',
      additional_fields: '',
      test_account_id: '',
      test_account_key: '',
      test_third_party_key: '',
      date_created: '2015-05-26T17:49:56-0700',
      date_modified: '2015-05-26T17:49:56-0700',
    },
  ],

  fraud_protections: [
    {
      id: 0,
      store_id: 0,
      payment_method_set_id: 0,
      type: 'google_recaptcha',
      description: 'Default fraud protection',
      json: '{"private_key":"","site_key":"","config":"disabled"}',
      score_threshold_reject: 0,
      date_created: '2015-05-27T08:59:54-0700',
      date_modified: '2015-05-27T08:59:54-0700',
    },
  ],

  payment_method_sets: [
    {
      id: 0,
      store_id: 0,
      payment_gateway_id: 0,
      gateway_uri: 'https://demo.api/hapi/payment_gateways/0',
      description: 'Default Payment Method Set',
      is_live: false,
      is_purchase_order_enabled: true,
      date_created: '2012-08-10T11:58:54-0700',
      date_modified: '2012-08-10T11:58:54-0700',
    },
    {
      id: 1,
      store_id: 0,
      gateway_uri: '',
      description: 'Empty Payment Method Set',
      is_live: false,
      is_purchase_order_enabled: true,
      date_created: '2012-08-10T11:58:54-0700',
      date_modified: '2012-08-10T11:58:54-0700',
    },
  ],

  payment_method_set_hosted_payment_gateways: [
    {
      id: 0,
      store_id: 0,
      payment_method_set_id: 0,
      hosted_payment_gateway_id: 0,
      payment_method_set_uri: 'https://demo.api/hapi/payment_method_sets/0',
      hosted_payment_gateway_uri: 'https://demo.api/hapi/hosted_payment_gateways/0',
      date_created: '2012-08-10T11:58:54-0700',
      date_modified: '2012-08-10T11:58:54-0700',
    },
  ],

  payment_method_set_fraud_protections: [
    {
      id: 0,
      store_id: 0,
      payment_method_set_id: 0,
      fraud_protection_id: 0,
      payment_method_set_uri: 'https://demo.api/hapi/payment_method_sets/0',
      fraud_protection_uri: 'https://demo.api/hapi/fraud_protections/0',
      date_created: '2012-08-10T11:58:54-0700',
      date_modified: '2012-08-10T11:58:54-0700',
    },
  ],

  property_helpers: [
    {
      id: 0,
      store_id: 0,
      message: 'fx:payment_gateways property helper',
      values: {
        authorize: {
          name: 'Authorize.net AIM',
          id_description: 'API ID',
          test_id: 'BxFSnPy7',
          key_description: 'Transaction Key',
          test_key: '8SPBTpqs4uf2ZwM8',
          third_party_key_description: '',
          test_third_party_key: '',
          supports_auth_only: true,
          supports_3d_secure: true,
          additional_fields: null,
        },
      },
    },
    {
      id: 1,
      store_id: 0,
      message: 'fx:hosted_payment_gateways property helper',
      values: {
        amazon_mws: {
          name: 'Amazon Pay',
          id_description: 'Seller ID',
          test_id: '',
          key_description: 'MWS Auth Token',
          test_key: '',
          third_party_key_description: 'Client ID',
          test_third_party_key: '',
          supports_auth_only: false,
          supports_3d_secure: false,
          additional_fields: {
            blocks: [
              {
                id: 'amazon_mws_additonal_fields',
                parent_id: 'gateway_live_amazon_mws',
                is_live: true,
                fields: [
                  {
                    id: 'on_amazon_mws_auth',
                    name: 'Authorize only (do not capture funds)',
                    type: 'checkbox',
                    default_value: false,
                  },
                ],
              },
              {
                id: 'test_amazon_mws_additonal_fields',
                parent_id: 'gateway_test_amazon_mws',
                is_live: false,
                fields: [
                  {
                    id: 'test_on_amazon_mws_auth',
                    name: 'Authorize only (do not capture funds)',
                    type: 'checkbox',
                    default_value: false,
                  },
                ],
              },
            ],
          },
        },
        klarna: {
          name: 'Klarna Payments',
          id_description: 'API username',
          test_id: 'PK09997_741be585df8f',
          key_description: 'API password',
          test_key: 'YOeGaRTZvbvVgm6m',
          third_party_key_description: '',
          test_third_party_key: '',
          supports_auth_only: false,
          supports_3d_secure: false,
          additional_fields: {
            blocks: [
              {
                id: 'klarna_additional_fields',
                parent_id: 'gateway_live_klarna',
                fields: [
                  {
                    id: 'klarna_auth',
                    name: 'Authorize only (do not capture funds)',
                    type: 'checkbox',
                    default_value: false,
                  },
                  {
                    id: 'klarna_continent_endpoint',
                    name: 'Merchant Account Continent',
                    description: 'Location of your Klarna account',
                    type: 'select',
                    default_value: 'EU',
                    options: [
                      {
                        name: 'Europe',
                        value: 'EU',
                      },
                      {
                        name: 'North America',
                        value: 'NA',
                      },
                      {
                        name: 'Oceania',
                        value: 'OC',
                      },
                    ],
                  },
                ],
                is_live: true,
              },
              {
                id: 'test_klarna_additional_fields',
                parent_id: 'gateway_test_klarna',
                fields: [
                  {
                    id: 'test_klarna_auth',
                    name: 'Authorize only (do not capture funds)',
                    type: 'checkbox',
                    default_value: false,
                  },
                  {
                    id: 'test_klarna_continent_endpoint',
                    name: 'Merchant Account Continent',
                    description: 'Location of your Klarna account',
                    type: 'select',
                    default_value: 'EU',
                    options: [
                      {
                        name: 'Europe',
                        value: 'EU',
                      },
                      {
                        name: 'North America',
                        value: 'NA',
                      },
                      {
                        name: 'Oceania',
                        value: 'OC',
                      },
                    ],
                  },
                ],
                is_live: false,
              },
            ],
          },
        },
      },
    },
    {
      id: 2,
      message: 'fx:timezones property helper',
      values: {
        timezone: [
          {
            timezone: 'America/Los_Angeles',
            description: '(GMT-08:00) Pacific Time (US and Canada)',
          },
          {
            timezone: 'America/Denver',
            description: '(GMT-07:00) Mountain Time (US and Canada)',
          },
          {
            timezone: 'America/Regina',
            description: '(GMT-06:00) Saskatchewan',
          },
        ],
      },
    },
    {
      id: 3,
      message: 'fx:countries property helper',
      values: {
        GB: {
          default: 'United Kingdom',
          cc2: 'GB',
          cc3: 'GBR',
          alternate_values: ['Great Britain', 'England', 'Northern Ireland', 'Britain', 'UK'],
          boost: 4,
          has_regions: false,
          regions_required: false,
          regions_type: 'county',
          active: true,
        },
        US: {
          default: 'United States',
          cc2: 'US',
          cc3: 'USA',
          alternate_values: ['USA', 'United States of America', 'America'],
          boost: 4.5,
          has_regions: true,
          regions_required: true,
          regions_type: 'state',
          active: true,
        },
        UM: {
          default: 'United States Minor Outlying Islands',
          cc2: 'UM',
          cc3: 'UMI',
          alternate_values: [],
          boost: 1,
          has_regions: false,
          regions_required: false,
          regions_type: 'state',
          active: true,
        },
      },
    },
    {
      id: 4,
      message: 'fx:regions property helper',
      values: {
        SD: {
          default: 'South Dakota',
          code: 'SD',
          alternate_values: [],
          boost: 1,
          active: true,
        },
        TN: {
          default: 'Tennessee',
          code: 'TN',
          alternate_values: [],
          boost: 1,
          active: true,
        },
        TX: {
          default: 'Texas',
          code: 'TX',
          alternate_values: [],
          boost: 1,
          active: true,
        },
      },
    },
    {
      id: 5,
      message: 'fx:shipping_address_types property helper',
      values: {
        residential: 'Rate as Residential',
        commercial: 'Rate as Commercial',
        determine_by_company: 'Rate based on Company field',
      },
    },
    {
      id: 6,
      message: 'fx:languages property helper',
      values: {
        dutch: 'Dutch',
        english: 'English',
        spanish: 'Spanish',
        swedish: 'Swedish',
        finnish: 'Finnish',
        french: 'French',
        german: 'German',
        chinese: 'Chinese',
        norwegian: 'Norwegian',
        italian: 'Italian',
      },
    },
    {
      id: 7,
      message: 'fx:locale_codes property helper',
      values: {
        en_AU: 'English locale for Australia (Currency: AUD:$)',
        en_BW: 'English locale for Botswana (Currency: BWP:Pu)',
        en_CA: 'English locale for Canada (Currency: CAD:$)',
        en_DK: 'English locale for Denmark (Currency: DKK:kr)',
        en_GB: 'English locale for Britain (Currency: GBP:&pound;)',
        en_HK: 'English locale for Hong Kong (Currency: HKD:HK$)',
        en_IE: 'English locale for Ireland (Currency: EUR:&euro;)',
        en_IN: 'English locale for India (Currency: INR:₨)',
        en_NZ: 'English locale for New Zealand (Currency: NZD:$)',
        en_PH: 'English locale for Philippines (Currency: PHP:Php)',
        en_SG: 'English locale for Singapore (Currency: SGD:$)',
        en_US: 'English locale for the USA (Currency: USD:$)',
        en_ZA: 'English locale for South Africa (Currency: ZAR:R)',
        en_ZW: 'English locale for Zimbabwe (Currency: ZWD:Z$)',
        en_GH: 'English locale for Ghana (Currency: GHS:GHc)',
      },
    },
    {
      id: 8,
      message: 'fx:checkout_types property helper',
      values: {
        default_account: 'Allow guest and customer accounts, default to account',
        default_guest: 'Allow guest and customer accounts, default to guest',
        account_only: 'Allow customer accounts only',
        guest_only: 'Allow guests only',
      },
    },
    {
      id: 9,
      message: 'fx:customer_password_hash_types property helper',
      values: {
        concrete5: {
          description: 'Concrete5',
          config: "Enter your 'PASSWORD_SALT' from your site.php file here.",
        },
        phpass: {
          description: 'phpass, portable mode (Wordpress, osCommerce 2.3+, etc.)',
          config: 8,
        },
        pbkdf2: {
          description: 'RSA PBKDF2 (for MODX Revolution)',
          config: '1000, 32, sha256',
        },
      },
    },
    {
      id: 10,
      message: 'fx:language_strings property helper',
      values: {
        english: {
          cart_add_coupon: 'Add Coupon',
          cart_add_coupon_and_gift_card: 'Add Coupon or Gift Card',
          cart_add_gift_card: 'Add Gift Card',
          checkout_ach_account_number: 'Account number',
          checkout_ach_name_account: 'Name on account',
          checkout_ach_the_owner:
            'I represent that I am the owner and/or authorized signer on the checking account above',
          minfraud_highrisk_transaction:
            'Error: This transaction exceeds our fraud risk settings and cannot be processed. Please contact us directly to process your order.',
          minfraud_api_error: 'MinFraud API Error:',
          receipt_id_error:
            "We're sorry, but we could not retrieve the receipt you requested. If you arrived here via your browser's back button, the receipt has expired for security reasons. You can revisit this receipt by clicking the link in the email you received. If you arrived here after clicking on a link in an email, please ensure that the entire text of the link is included in your browser's address bar. You can do this by copying the link, modifying it, and pasting it into the address bar as a single line.",
          gateways: {
            cybersource: {},
            paypal_plus: {
              reference_number: 'Reference Number',
              bank_name: 'Bank Name',
              account_holder_name: 'Account Holder Name',
              international_bank_account_number: 'IBAN',
              bank_identifier_code: 'Bank Identifier Code',
              payment_due_date: 'Payment Due Date',
            },
          },
        },
      },
    },
  ],

  template_sets: [
    {
      id: 0,
      store_id: 0,
      cart_template_id: 0,
      cart_include_template_id: 0,
      checkout_template_id: 0,
      receipt_template_id: 0,
      email_template_id: 0,
      payment_method_set_id: 0,
      template_config_id: 0,
      cart_template_uri: 'https://demo.api/hapi/cart_templates/0',
      cart_include_template_uri: 'https://demo.api/hapi/cart_include_templates/0',
      checkout_template_uri: 'https://demo.api/hapi/checkout_templates/0',
      receipt_template_uri: 'https://demo.api/hapi/receipt_templates/0',
      email_template_uri: 'https://demo.api/hapi/email_templates/0',
      payment_method_set_uri: 'https://demo.api/hapi/payment_method_sets/0',
      template_config_uri: 'https://demo.api/hapi/template_configs/0',
      code: 'DEFAULT',
      description: 'Default Template Set',
      language: 'english',
      locale_code: 'en_US',
      config: '',
      date_created: '2012-08-10T11:58:54-0700',
      date_modified: '2012-08-10T11:58:54-0700',
    },
    {
      id: 1,
      store_id: 0,
      cart_template_id: 0,
      cart_include_template_id: 0,
      checkout_template_id: 0,
      receipt_template_id: 0,
      email_template_id: 0,
      payment_method_set_id: 0,
      template_config_id: 0,
      cart_template_uri: 'https://demo.api/hapi/cart_templates/0',
      cart_include_template_uri: 'https://demo.api/hapi/cart_include_templates/0',
      checkout_template_uri: 'https://demo.api/hapi/checkout_templates/0',
      receipt_template_uri: 'https://demo.api/hapi/receipt_templates/0',
      email_template_uri: 'https://demo.api/hapi/email_templates/0',
      payment_method_set_uri: 'https://demo.api/hapi/payment_method_sets/0',
      template_config_uri: 'https://demo.api/hapi/template_configs/0',
      code: 'TEST',
      description: 'Test (Localdev)',
      language: 'english',
      locale_code: 'en_US',
      config: '',
      date_created: '2012-08-10T11:58:54-0700',
      date_modified: '2012-08-10T11:58:54-0700',
    },
  ],

  store_versions: [
    {
      id: 0,
      version: '1.1',
      changelog_blog_url: 'http://www.foxycart.com/blog/1.1',
      changelog_url: 'https://admin.foxycart.com/v/1.1.0/changelog.html',
      changelog_content: '',
      cart_types: {
        colorbox: {
          javascript_library: {
            name: 'JQuery',
            version: '1.9.0',
            url: '//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js',
          },
          javascript: ['//cdn.foxycart.com/{{ store_domain }}/foxycart.colorbox.js?ver=2'],
          css: ['//cdn.foxycart.com/static/scripts/colorbox/1.3.23/style1_fc/colorbox.css?ver=1'],
        },
        none: {
          javascript_library: {
            name: 'JQuery',
            version: '1.9.0',
            url: '//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js',
          },
          javascript: ['//cdn.foxycart.com/{{ store_domain }}/foxycart.js?ver=2'],
          css: [],
        },
      },
      version_date: '2013-01-22T15:21:11-08:00',
      is_visible: true,
      is_beta: false,
      date_created: '2013-01-22T15:21:11-08:00',
      date_modified: '2013-01-22T15:21:11-08:00',
    },
    {
      id: 1,
      version: '2.0',
      changelog_blog_url: 'http://www.foxycart.com/blog/2.0',
      changelog_url: 'https://admin.foxycart.com/v/2.0.0/changelog.html',
      changelog_content: '',
      cart_types: {
        default: {
          javascript_library: [],
          javascript: ['https://cdn.foxycart.com/{{ store_domain }}/loader.js'],
          css: [],
        },
      },
      version_date: '2014-04-21T15:17:36-07:00',
      is_visible: true,
      is_beta: false,
      date_created: '2014-04-21T15:17:36-07:00',
      date_modified: '2014-04-21T15:17:36-07:00',
    },
  ],

  integrations: [
    {
      id: 0,
      user_id: 0,
      store_id: 0,
      user_uri: 'https://demo.api/hapi/users/0',
      client_id: 'client_TS5yEGRgsk7KZIeKhdIz',
      scope: 'webhook store_id_9',
      expires: 1947549287,
      project_name: 'ACME Widgets',
      project_description: 'Sample integration project for testing.',
      company_name: 'ACME',
      company_url: '',
      company_logo: '',
      contact_name: 'John Doe',
      contact_email: 'john.doe@example.com',
      added_by_name: 'Sally Sims',
      added_by_email: 'sally.sims@example.com',
    },
  ],

  language_overrides: [
    {
      id: 0,
      store_id: 0,
      template_set_id: 0,
      code: 'cart_add_coupon',
      gateway: '',
      custom_value: 'I have a coupon',
      date_created: null,
      date_modified: null,
    },
    {
      id: 1,
      store_id: 0,
      template_set_id: 0,
      code: 'bank_identifier_code',
      gateway: 'paypal_plus',
      custom_value: 'BIC',
      date_created: null,
      date_modified: null,
    },
  ],

  subscription_settings: [
    {
      id: 0,
      store_id: 0,
      automatically_charge_past_due_amount: true,
      send_email_receipts_for_automated_billing: true,
      reattempt_schedule: '',
      reattempt_bypass_logic: 'skip_if_exists',
      reattempt_bypass_strings: '',
      reminder_email_schedule: '2, 10, 18, 26',
      reset_nextdate_on_makeup_payment: false,
      past_due_amount_handling: 'increment',
      prevent_customer_cancel_with_past_due: false,
      cancellation_schedule: '',
      expiring_soon_payment_reminder_schedule: '30, 15',
      modification_url: '',
      date_created: '2020-05-13T12:11:12-07:00',
      date_modified: '2020-05-13T12:11:12-07:00',
    },
  ],

  applied_coupon_codes: [
    {
      id: 0,
      cart_id: 0,
      store_id: 0,
      coupon_id: 0,
      coupon_code_id: 0,
      code: 'OCTBRSL220',
      date_created: '2015-04-27T13:42:55-0700',
      date_modified: '2015-04-27T13:42:55-0700',
    },
  ],

  native_integrations: [
    {
      id: 0,
      store_id: 0,
      provider: 'avalara',
      config:
        '{"service_url":"https://development.avalara.net/","id":"12345678","key":"ASDFJASDFKJASDFKJ","company_code":"CompanyCode","use_ava_tax":true,"create_invoice":true,"use_address_validation":false,"address_validation_countries":[],"category_to_product_tax_code_mappings":{"1005":"PS081258","955":"qweasz2","956":"","2425":""}}',
      date_created: '2016-03-24T11:02:40-0700',
      date_modified: '2016-03-31T12:15:41-0700',
    },
    {
      id: 1,
      store_id: 0,
      provider: 'webhook',
      config:
        '{"service":"json","encryption_key":"1T6478TKJ9S5BHB73K0NTGDZ824X3HZ2","title":"My JSON Webhook","version":1,"url":"https:\\/\\/www.example.com\\/webhook.php","events":["transaction\\/created"]}',
      date_created: '2018-01-01T04:30:53-0700',
      date_modified: '2018-01-01T04:30:53-0700',
    },
  ],
});
