import { Graph, Rels } from '@foxy.io/sdk/customer';

import { Templates as AddressCardTemplates } from '../AddressCard/types';
import { Templates as AddressFormTemplates } from '../AddressForm/types';
import { Templates as AttributeCardTemplates } from '../AttributeCard/types';
import { Templates as AttributeFormTemplates } from '../AttributeForm/types';
import { Customer } from './Customer';
import { Templates as CustomerFormTemplates } from '../CustomerForm/types';
import { Templates as PaymentMethodCardTemplates } from '../PaymentMethodCard/types';
import { Renderer } from '../../../mixins/configurable';
import { Resource } from '@foxy.io/sdk/core';
import { Templates as SubscriptionFormTemplates } from '../SubscriptionForm/types';
import { Templates as SubscriptionsTableTemplates } from '../SubscriptionsTable/types';
import { TemplateResult } from 'lit-html';
import { Templates as TransactionsTableTemplates } from '../TransactionsTable/types';

export type CustomerAddresses = Resource<Rels.CustomerAddresses>;
export type Attributes = Resource<Rels.Attributes>;
export type Data = Resource<Graph>;
export type Tab = { title: string; content: TemplateResult };

export type Templates = {
  'header:before'?: Renderer<Customer>;
  'header:after'?: Renderer<Customer>;
  'header:actions:before'?: Renderer<Customer>;
  'header:actions:after'?: Renderer<Customer>;
  'header:actions:edit:before'?: Renderer<Customer>;
  'header:actions:edit:after'?: Renderer<Customer>;
  'header:actions:edit:form:first-name:before'?: CustomerFormTemplates['first-name:before'];
  'header:actions:edit:form:first-name:after'?: CustomerFormTemplates['first-name:after'];
  'header:actions:edit:form:last-name:before'?: CustomerFormTemplates['last-name:before'];
  'header:actions:edit:form:last-name:after'?: CustomerFormTemplates['last-name:after'];
  'header:actions:edit:form:email:before'?: CustomerFormTemplates['email:before'];
  'header:actions:edit:form:email:after'?: CustomerFormTemplates['email:after'];
  'header:actions:edit:form:tax-id:before'?: CustomerFormTemplates['tax-id:before'];
  'header:actions:edit:form:tax-id:after'?: CustomerFormTemplates['tax-id:after'];
  'header:actions:edit:form:timestamps:before'?: CustomerFormTemplates['timestamps:before'];
  'header:actions:edit:form:timestamps:after'?: CustomerFormTemplates['timestamps:after'];
  'header:actions:edit:form:delete:before'?: CustomerFormTemplates['delete:before'];
  'header:actions:edit:form:delete:after'?: CustomerFormTemplates['delete:after'];
  'header:actions:edit:form:create:before'?: CustomerFormTemplates['create:before'];
  'header:actions:edit:form:create:after'?: CustomerFormTemplates['create:after'];
  'default'?: Renderer<Customer>;
  'addresses:before'?: Renderer<Customer>;
  'addresses:after'?: Renderer<Customer>;
  'addresses:actions:before'?: Renderer<Customer>;
  'addresses:actions:after'?: Renderer<Customer>;
  'addresses:actions:create:before'?: Renderer<Customer>;
  'addresses:actions:create:after'?: Renderer<Customer>;
  'addresses:actions:create:form:address-name:before'?: AddressFormTemplates['address-name:before'];
  'addresses:actions:create:form:address-name:after'?: AddressFormTemplates['address-name:after'];
  'addresses:actions:create:form:first-name:before'?: AddressFormTemplates['first-name:before'];
  'addresses:actions:create:form:first-name:after'?: AddressFormTemplates['first-name:after'];
  'addresses:actions:create:form:last-name:before'?: AddressFormTemplates['last-name:before'];
  'addresses:actions:create:form:last-name:after'?: AddressFormTemplates['last-name:after'];
  'addresses:actions:create:form:region:before'?: AddressFormTemplates['region:before'];
  'addresses:actions:create:form:region:after'?: AddressFormTemplates['region:after'];
  'addresses:actions:create:form:city:before'?: AddressFormTemplates['city:before'];
  'addresses:actions:create:form:city:after'?: AddressFormTemplates['city:after'];
  'addresses:actions:create:form:phone:before'?: AddressFormTemplates['phone:before'];
  'addresses:actions:create:form:phone:after'?: AddressFormTemplates['phone:after'];
  'addresses:actions:create:form:company:before'?: AddressFormTemplates['company:before'];
  'addresses:actions:create:form:company:after'?: AddressFormTemplates['company:after'];
  'addresses:actions:create:form:address-line-one:before'?: AddressFormTemplates['address-line-one:before'];
  'addresses:actions:create:form:address-line-one:after'?: AddressFormTemplates['address-line-one:after'];
  'addresses:actions:create:form:address-line-two:before'?: AddressFormTemplates['address-line-two:before'];
  'addresses:actions:create:form:address-line-two:after'?: AddressFormTemplates['address-line-two:after'];
  'addresses:actions:create:form:postal-code:before'?: AddressFormTemplates['postal-code:before'];
  'addresses:actions:create:form:postal-code:after'?: AddressFormTemplates['postal-code:after'];
  'addresses:actions:create:form:timestamps:before'?: AddressFormTemplates['timestamps:before'];
  'addresses:actions:create:form:timestamps:after'?: AddressFormTemplates['timestamps:after'];
  'addresses:actions:create:form:delete:before'?: AddressFormTemplates['delete:before'];
  'addresses:actions:create:form:delete:after'?: AddressFormTemplates['delete:after'];
  'addresses:actions:create:form:create:before'?: AddressFormTemplates['create:before'];
  'addresses:actions:create:form:create:after'?: AddressFormTemplates['create:after'];
  'addresses:list:before'?: Renderer<Customer>;
  'addresses:list:after'?: Renderer<Customer>;
  'addresses:list:card:address-name:before'?: AddressCardTemplates['address-name:before'];
  'addresses:list:card:address-name:after'?: AddressCardTemplates['address-name:after'];
  'addresses:list:card:full-name:before'?: AddressCardTemplates['full-name:before'];
  'addresses:list:card:full-name:after'?: AddressCardTemplates['full-name:after'];
  'addresses:list:card:full-address:before'?: AddressCardTemplates['full-address:before'];
  'addresses:list:card:full-address:after'?: AddressCardTemplates['full-address:after'];
  'addresses:list:card:company:before'?: AddressCardTemplates['company:before'];
  'addresses:list:card:company:after'?: AddressCardTemplates['company:after'];
  'addresses:list:card:phone:before'?: AddressCardTemplates['phone:before'];
  'addresses:list:card:phone:after'?: AddressCardTemplates['phone:after'];
  'addresses:list:form:address-name:before'?: AddressFormTemplates['address-name:before'];
  'addresses:list:form:address-name:after'?: AddressFormTemplates['address-name:after'];
  'addresses:list:form:first-name:before'?: AddressFormTemplates['first-name:before'];
  'addresses:list:form:first-name:after'?: AddressFormTemplates['first-name:after'];
  'addresses:list:form:last-name:before'?: AddressFormTemplates['last-name:before'];
  'addresses:list:form:last-name:after'?: AddressFormTemplates['last-name:after'];
  'addresses:list:form:region:before'?: AddressFormTemplates['region:before'];
  'addresses:list:form:region:after'?: AddressFormTemplates['region:after'];
  'addresses:list:form:city:before'?: AddressFormTemplates['city:before'];
  'addresses:list:form:city:after'?: AddressFormTemplates['city:after'];
  'addresses:list:form:phone:before'?: AddressFormTemplates['phone:before'];
  'addresses:list:form:phone:after'?: AddressFormTemplates['phone:after'];
  'addresses:list:form:company:before'?: AddressFormTemplates['company:before'];
  'addresses:list:form:company:after'?: AddressFormTemplates['company:after'];
  'addresses:list:form:address-line-one:before'?: AddressFormTemplates['address-line-one:before'];
  'addresses:list:form:address-line-one:after'?: AddressFormTemplates['address-line-one:after'];
  'addresses:list:form:address-line-two:before'?: AddressFormTemplates['address-line-two:before'];
  'addresses:list:form:address-line-two:after'?: AddressFormTemplates['address-line-two:after'];
  'addresses:list:form:postal-code:before'?: AddressFormTemplates['postal-code:before'];
  'addresses:list:form:postal-code:after'?: AddressFormTemplates['postal-code:after'];
  'addresses:list:form:timestamps:before'?: AddressFormTemplates['timestamps:before'];
  'addresses:list:form:timestamps:after'?: AddressFormTemplates['timestamps:after'];
  'addresses:list:form:delete:before'?: AddressFormTemplates['delete:before'];
  'addresses:list:form:delete:after'?: AddressFormTemplates['delete:after'];
  'addresses:list:form:create:before'?: AddressFormTemplates['create:before'];
  'addresses:list:form:create:after'?: AddressFormTemplates['create:after'];
  'payment-methods:before'?: Renderer<Customer>;
  'payment-methods:after'?: Renderer<Customer>;
  'payment-methods:list:before'?: Renderer<Customer>;
  'payment-methods:list:after'?: Renderer<Customer>;
  'payment-methods:list:card:actions:before'?: PaymentMethodCardTemplates['actions:before'];
  'payment-methods:list:card:actions:after'?: PaymentMethodCardTemplates['actions:after'];
  'payment-methods:list:card:actions:delete:before'?: PaymentMethodCardTemplates['actions:delete:before'];
  'payment-methods:list:card:actions:delete:after'?: PaymentMethodCardTemplates['actions:delete:after'];
  'attributes:before'?: Renderer<Customer>;
  'attributes:after'?: Renderer<Customer>;
  'attributes:actions:before'?: Renderer<Customer>;
  'attributes:actions:after'?: Renderer<Customer>;
  'attributes:actions:create:before'?: Renderer<Customer>;
  'attributes:actions:create:after'?: Renderer<Customer>;
  'attributes:actions:create:form:name:before'?: AttributeFormTemplates['name:before'];
  'attributes:actions:create:form:name:after'?: AttributeFormTemplates['name:after'];
  'attributes:actions:create:form:value:before'?: AttributeFormTemplates['value:before'];
  'attributes:actions:create:form:value:after'?: AttributeFormTemplates['value:after'];
  'attributes:actions:create:form:visibility:before'?: AttributeFormTemplates['visibility:before'];
  'attributes:actions:create:form:visibility:after'?: AttributeFormTemplates['visibility:after'];
  'attributes:actions:create:form:timestamps:before'?: AttributeFormTemplates['timestamps:before'];
  'attributes:actions:create:form:timestamps:after'?: AttributeFormTemplates['timestamps:after'];
  'attributes:actions:create:form:delete:before'?: AttributeFormTemplates['delete:before'];
  'attributes:actions:create:form:delete:after'?: AttributeFormTemplates['delete:after'];
  'attributes:actions:create:form:create:before'?: AttributeFormTemplates['create:before'];
  'attributes:actions:create:form:create:after'?: AttributeFormTemplates['create:after'];
  'attributes:list:before'?: Renderer<Customer>;
  'attributes:list:after'?: Renderer<Customer>;
  'attributes:list:card:name:before'?: AttributeCardTemplates['name:before'];
  'attributes:list:card:name:after'?: AttributeCardTemplates['name:after'];
  'attributes:list:card:value:before'?: AttributeCardTemplates['value:before'];
  'attributes:list:card:value:after'?: AttributeCardTemplates['value:after'];
  'attributes:list:form:name:before'?: AttributeFormTemplates['name:before'];
  'attributes:list:form:name:after'?: AttributeFormTemplates['name:after'];
  'attributes:list:form:value:before'?: AttributeFormTemplates['value:before'];
  'attributes:list:form:value:after'?: AttributeFormTemplates['value:after'];
  'attributes:list:form:visibility:before'?: AttributeFormTemplates['visibility:before'];
  'attributes:list:form:visibility:after'?: AttributeFormTemplates['visibility:after'];
  'attributes:list:form:timestamps:before'?: AttributeFormTemplates['timestamps:before'];
  'attributes:list:form:timestamps:after'?: AttributeFormTemplates['timestamps:after'];
  'attributes:list:form:delete:before'?: AttributeFormTemplates['delete:before'];
  'attributes:list:form:delete:after'?: AttributeFormTemplates['delete:after'];
  'attributes:list:form:create:before'?: AttributeFormTemplates['create:before'];
  'attributes:list:form:create:after'?: AttributeFormTemplates['create:after'];
  'transactions:before'?: Renderer<Customer>;
  'transactions:after'?: Renderer<Customer>;
  'transactions:table:default'?: Renderer<TransactionsTableTemplates['default']>;
  'subscriptions:before'?: Renderer<Customer>;
  'subscriptions:after'?: Renderer<Customer>;
  'subscriptions:form:header:before'?: SubscriptionFormTemplates['header:before'];
  'subscriptions:form:header:after'?: SubscriptionFormTemplates['header:after'];
  'subscriptions:form:items:before'?: SubscriptionFormTemplates['items:before'];
  'subscriptions:form:items:after'?: SubscriptionFormTemplates['items:after'];
  'subscriptions:form:items:actions:before'?: SubscriptionFormTemplates['items:actions:before'];
  'subscriptions:form:items:actions:after'?: SubscriptionFormTemplates['items:actions:after'];
  'subscriptions:form:end-date:before'?: SubscriptionFormTemplates['end-date:before'];
  'subscriptions:form:end-date:after'?: SubscriptionFormTemplates['end-date:after'];
  'subscriptions:form:end-date:form:warning:before'?: SubscriptionFormTemplates['end-date:form:warning:before'];
  'subscriptions:form:end-date:form:warning:after'?: SubscriptionFormTemplates['end-date:form:warning:after'];
  'subscriptions:form:end-date:form:end-date:before'?: SubscriptionFormTemplates['end-date:form:end-date:before'];
  'subscriptions:form:end-date:form:end-date:after'?: SubscriptionFormTemplates['end-date:form:end-date:after'];
  'subscriptions:form:end-date:form:submit:before'?: SubscriptionFormTemplates['end-date:form:submit:before'];
  'subscriptions:form:end-date:form:submit:after'?: SubscriptionFormTemplates['end-date:form:submit:after'];
  'subscriptions:form:next-transaction-date:before'?: SubscriptionFormTemplates['next-transaction-date:before'];
  'subscriptions:form:next-transaction-date:after'?: SubscriptionFormTemplates['next-transaction-date:after'];
  'subscriptions:form:frequency:before'?: SubscriptionFormTemplates['frequency:before'];
  'subscriptions:form:frequency:after'?: SubscriptionFormTemplates['frequency:after'];
  'subscriptions:form:transactions:before'?: SubscriptionFormTemplates['transactions:before'];
  'subscriptions:form:transactions:after'?: SubscriptionFormTemplates['transactions:after'];
  'subscriptions:table:default'?: Renderer<SubscriptionsTableTemplates['default']>;
};
