import type { Resource } from '@foxy.io/sdk/core';
import type { CartForm } from './CartForm';
import type { Renderer } from '../../../mixins/configurable';
import type { Rels } from '@foxy.io/sdk/backend';

export type Data = Resource<Rels.Cart>;
export type Templates = {
  'customer-type:before'?: Renderer<CartForm>;
  'customer-type:after'?: Renderer<CartForm>;
  'customer:before'?: Renderer<CartForm>;
  'customer:after'?: Renderer<CartForm>;
  'template-set-uri:before'?: Renderer<CartForm>;
  'template-set-uri:after'?: Renderer<CartForm>;
  'items:before'?: Renderer<CartForm>;
  'items:after'?: Renderer<CartForm>;
  'applied-coupon-codes:before'?: Renderer<CartForm>;
  'applied-coupon-codes:after'?: Renderer<CartForm>;
  'custom-fields:before'?: Renderer<CartForm>;
  'custom-fields:after'?: Renderer<CartForm>;
  'attributes:before'?: Renderer<CartForm>;
  'attributes:after'?: Renderer<CartForm>;
  'billing-first-name:before'?: Renderer<CartForm>;
  'billing-first-name:after'?: Renderer<CartForm>;
  'billing-last-name:before'?: Renderer<CartForm>;
  'billing-last-name:after'?: Renderer<CartForm>;
  'billing-company:before'?: Renderer<CartForm>;
  'billing-company:after'?: Renderer<CartForm>;
  'billing-phone:before'?: Renderer<CartForm>;
  'billing-phone:after'?: Renderer<CartForm>;
  'billing-address-one:before'?: Renderer<CartForm>;
  'billing-address-one:after'?: Renderer<CartForm>;
  'billing-address-two:before'?: Renderer<CartForm>;
  'billing-address-two:after'?: Renderer<CartForm>;
  'billing-country:before'?: Renderer<CartForm>;
  'billing-country:after'?: Renderer<CartForm>;
  'billing-region:before'?: Renderer<CartForm>;
  'billing-region:after'?: Renderer<CartForm>;
  'billing-city:before'?: Renderer<CartForm>;
  'billing-city:after'?: Renderer<CartForm>;
  'billing-postal-code:before'?: Renderer<CartForm>;
  'billing-postal-code:after'?: Renderer<CartForm>;
  'shipping-first-name:before'?: Renderer<CartForm>;
  'shipping-first-name:after'?: Renderer<CartForm>;
  'shipping-last-name:before'?: Renderer<CartForm>;
  'shipping-last-name:after'?: Renderer<CartForm>;
  'shipping-company:before'?: Renderer<CartForm>;
  'shipping-company:after'?: Renderer<CartForm>;
  'shipping-phone:before'?: Renderer<CartForm>;
  'shipping-phone:after'?: Renderer<CartForm>;
  'shipping-address-one:before'?: Renderer<CartForm>;
  'shipping-address-one:after'?: Renderer<CartForm>;
  'shipping-address-two:before'?: Renderer<CartForm>;
  'shipping-address-two:after'?: Renderer<CartForm>;
  'shipping-country:before'?: Renderer<CartForm>;
  'shipping-country:after'?: Renderer<CartForm>;
  'shipping-region:before'?: Renderer<CartForm>;
  'shipping-region:after'?: Renderer<CartForm>;
  'shipping-city:before'?: Renderer<CartForm>;
  'shipping-city:after'?: Renderer<CartForm>;
  'shipping-postal-code:before'?: Renderer<CartForm>;
  'shipping-postal-code:after'?: Renderer<CartForm>;
  'view-as-customer:before'?: Renderer<CartForm>;
  'view-as-customer:after'?: Renderer<CartForm>;
  'delete:before'?: Renderer<CartForm>;
  'delete:after'?: Renderer<CartForm>;
  'create:before'?: Renderer<CartForm>;
  'create:after'?: Renderer<CartForm>;
};
