import type { Rels as CustomerRels } from '@foxy.io/sdk/customer';
import type { Rels as BackendRels } from '@foxy.io/sdk/backend';
import type { Resource } from '@foxy.io/sdk/core';

export type Settings = Resource<CustomerRels.CustomerPortalSettings>;

export type Rel = BackendRels.Customer & {
  props: {
    /** When updating the password using Customer API, this value is required to complete the request. */
    password_old?: string;
    /** Client verification result. Required for customer registration via Customer API. */
    verification?: {
      /** Verification result, generated by hCaptcha. */
      token: string;
      /** Verification service type. Currently only hCaptcha is supported. */
      type: 'hcaptcha';
    };
  };
};

export type Data = Resource<Rel, undefined>;
