export const countries = {
  _links: {
    'curies': [{ name: 'fx', href: 'https://api.foxycart.com/rels/{rel}', templated: true }],
    'self': {
      href: 'https://demo.foxycart.com/s/admin/property_helpers/countries',
      title:
        'List of valid country values for any country setting such as the Store resource store_country.',
    },
    'fx:property_helpers': {
      href: 'https://demo.foxycart.com/s/admin/property_helpers',
      title: 'Property Helpers Home',
    },
  },
  message:
    'The values listed here are the correct values for the Store store_country field. The values are listed in the format value => description.',
  values: {
    AF: {
      default: 'Afghanistan',
      cc2: 'AF',
      cc3: 'AFG',
      alternate_values: ['Afghanestan', 'افغانستان'],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    AX: {
      default: 'Åland Islands',
      cc2: 'AX',
      cc3: 'ALA',
      alternate_values: ['Landskapet Åland', 'Aaland', 'Aland'],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    AL: {
      default: 'Albania',
      cc2: 'AL',
      cc3: 'ALB',
      alternate_values: ['Shqipëria'],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    DZ: {
      default: 'Algeria',
      cc2: 'DZ',
      cc3: 'DZA',
      alternate_values: ["Al-Jazā'ir", 'الجزائر'],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    AS: {
      default: 'American Samoa',
      cc2: 'AS',
      cc3: 'ASM',
      alternate_values: ['Amerika Sāmoa'],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    AD: {
      default: 'Andorra',
      cc2: 'AD',
      cc3: 'AND',
      alternate_values: [],
      boost: 0.7,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    AO: {
      default: 'Angola',
      cc2: 'AO',
      cc3: 'AGO',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    AI: {
      default: 'Anguilla',
      cc2: 'AI',
      cc3: 'AIA',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    AQ: {
      default: 'Antarctica',
      cc2: 'AQ',
      cc3: 'ATA',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    AG: {
      default: 'Antigua and Barbuda',
      cc2: 'AG',
      cc3: 'ATG',
      alternate_values: [],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    AR: {
      default: 'Argentina',
      cc2: 'AR',
      cc3: 'ARG',
      alternate_values: [],
      boost: 2.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    AM: {
      default: 'Armenia',
      cc2: 'AM',
      cc3: 'ARM',
      alternate_values: ['Hayastán', 'Հայաստան'],
      boost: 0.7,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    AW: {
      default: 'Aruba',
      cc2: 'AW',
      cc3: 'ABW',
      alternate_values: [],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    AU: {
      default: 'Australia',
      cc2: 'AU',
      cc3: 'AUS',
      alternate_values: [],
      boost: 4,
      has_regions: true,
      regions_required: true,
      regions_type: 'state',
      active: true,
    },
    AT: {
      default: 'Austria',
      cc2: 'AT',
      cc3: 'AUT',
      alternate_values: ['Österreich'],
      boost: 3,
      has_regions: true,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    AZ: {
      default: 'Azerbaijan',
      cc2: 'AZ',
      cc3: 'AZE',
      alternate_values: ['Azərbaycan'],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    BS: {
      default: 'Bahamas',
      cc2: 'BS',
      cc3: 'BHS',
      alternate_values: ['The Bahamas'],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    BH: {
      default: 'Bahrain',
      cc2: 'BH',
      cc3: 'BHR',
      alternate_values: ['Al-Baḥrayn', 'البحرين'],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    BD: {
      default: 'Bangladesh',
      cc2: 'BD',
      cc3: 'BGD',
      alternate_values: ['বাংলাদেশ'],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    BB: {
      default: 'Barbados',
      cc2: 'BB',
      cc3: 'BRB',
      alternate_values: [],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    BY: {
      default: 'Belarus',
      cc2: 'BY',
      cc3: 'BLR',
      alternate_values: ['Беларусь', 'Biełaruś', 'Belorussiya', 'Belorussiâ', 'Белоруссия'],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    BE: {
      default: 'Belgium',
      cc2: 'BE',
      cc3: 'BEL',
      alternate_values: ['België', 'Belgique', 'Belgien'],
      boost: 3,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    BZ: {
      default: 'Belize',
      cc2: 'BZ',
      cc3: 'BLZ',
      alternate_values: [],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    BJ: {
      default: 'Benin',
      cc2: 'BJ',
      cc3: 'BEN',
      alternate_values: ['Bénin'],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    BM: {
      default: 'Bermuda',
      cc2: 'BM',
      cc3: 'BMU',
      alternate_values: [],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    BT: {
      default: 'Bhutan',
      cc2: 'BT',
      cc3: 'BTN',
      alternate_values: ['Druk Yul', 'འབྲུག་ཡུལ'],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    BO: {
      default: 'Bolivia',
      cc2: 'BO',
      cc3: 'BOL',
      alternate_values: [
        'Bulivya Mamallaqta',
        'Wuliwya Suyu',
        'Volívia',
        'Bolivia, Plurinational State of',
      ],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    BQ: {
      default: 'Bonaire, Sint Eustatius and Saba',
      cc2: 'BQ',
      cc3: 'BES',
      alternate_values: [
        'Caribbean Netherlands',
        'Caribisch Nederland',
        'Bonaire',
        'Boneiru',
        'Sint Eustatius',
        'Statia',
        'Statius',
        'Saba',
      ],
      boost: 1.5,
      has_regions: true,
      regions_required: true,
      regions_type: 'state',
      active: true,
    },
    BA: {
      default: 'Bosnia and Herzegovina',
      cc2: 'BA',
      cc3: 'BIH',
      alternate_values: ['Bosna i Hercegovina', 'Босна и Херцеговина'],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    BW: {
      default: 'Botswana',
      cc2: 'BW',
      cc3: 'BWA',
      alternate_values: [],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    BV: {
      default: 'Bouvet Island',
      cc2: 'BV',
      cc3: 'BVT',
      alternate_values: ['Bouvetøya'],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    BR: {
      default: 'Brazil',
      cc2: 'BR',
      cc3: 'BRA',
      alternate_values: ['Brasil'],
      boost: 3,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    IO: {
      default: 'British Indian Ocean Territory',
      cc2: 'IO',
      cc3: 'IOT',
      alternate_values: ['Chagos Islands'],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    BN: {
      default: 'Brunei Darussalam',
      cc2: 'BN',
      cc3: 'BRN',
      alternate_values: ['بروني'],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    BG: {
      default: 'Bulgaria',
      cc2: 'BG',
      cc3: 'BGR',
      alternate_values: ['Bulgariya', 'Bălgarija', 'България'],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    BF: {
      default: 'Burkina Faso',
      cc2: 'BF',
      cc3: 'BFA',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    BI: {
      default: 'Burundi',
      cc2: 'BI',
      cc3: 'BDI',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    KH: {
      default: 'Cambodia',
      cc2: 'KH',
      cc3: 'KHM',
      alternate_values: ['Kampuchea', 'កម្ពុជា'],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    CM: {
      default: 'Cameroon',
      cc2: 'CM',
      cc3: 'CMR',
      alternate_values: ['Cameroun'],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    CA: {
      default: 'Canada',
      cc2: 'CA',
      cc3: 'CAN',
      alternate_values: [],
      boost: 4,
      has_regions: true,
      regions_required: true,
      regions_type: 'province',
      active: true,
    },
    CV: {
      default: 'Cape Verde',
      cc2: 'CV',
      cc3: 'CPV',
      alternate_values: ['Cabo Verde'],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    CW: {
      default: 'Curaçao',
      cc2: 'CW',
      cc3: 'CUW',
      alternate_values: ['Kòrsou'],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    KY: {
      default: 'Cayman Islands',
      cc2: 'KY',
      cc3: 'CYM',
      alternate_values: [],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    CF: {
      default: 'Central African Republic',
      cc2: 'CF',
      cc3: 'CAF',
      alternate_values: ['République Centrafricaine', 'Ködörösêse tî Bêafrîka'],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    TD: {
      default: 'Chad',
      cc2: 'TD',
      cc3: 'TCD',
      alternate_values: ['Tchad', 'Tšād', 'تشاد'],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    CL: {
      default: 'Chile',
      cc2: 'CL',
      cc3: 'CHL',
      alternate_values: [],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    CN: {
      default: 'China',
      cc2: 'CN',
      cc3: 'CHN',
      alternate_values: ['中国', 'Zhōngguó', 'Zhōnghuá Rénmín Gònghéguó'],
      boost: 2.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    CX: {
      default: 'Christmas Island',
      cc2: 'CX',
      cc3: 'CXR',
      alternate_values: [],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    CC: {
      default: 'Cocos (Keeling) Islands',
      cc2: 'CC',
      cc3: 'CCK',
      alternate_values: [],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    CO: {
      default: 'Colombia',
      cc2: 'CO',
      cc3: 'COL',
      alternate_values: [],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    KM: {
      default: 'Comoros',
      cc2: 'KM',
      cc3: 'COM',
      alternate_values: ['Komori', 'Juzur al-Qamar', 'جزر القمر', 'Comores'],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    CG: {
      default: 'Congo',
      cc2: 'CG',
      cc3: 'COG',
      alternate_values: ['Congo-Brazza'],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    CD: {
      default: 'Congo, the Democratic Republic of the',
      cc2: 'CD',
      cc3: 'COD',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    CK: {
      default: 'Cook Islands',
      cc2: 'CK',
      cc3: 'COK',
      alternate_values: [],
      boost: 0.7,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    CR: {
      default: 'Costa Rica',
      cc2: 'CR',
      cc3: 'CRI',
      alternate_values: [],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    CI: {
      default: 'Cote DIvoire',
      cc2: 'CI',
      cc3: 'CIV',
      alternate_values: ["Côte d'Ivoire"],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    HR: {
      default: 'Croatia',
      cc2: 'HR',
      cc3: 'HRV',
      alternate_values: ['Hrvatska'],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    CU: {
      default: 'Cuba',
      cc2: 'CU',
      cc3: 'CUB',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    CY: {
      default: 'Cyprus',
      cc2: 'CY',
      cc3: 'CYP',
      alternate_values: ['Kypros', 'Κύπρος', 'Kıbrıs'],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    CZ: {
      default: 'Czech Republic',
      cc2: 'CZ',
      cc3: 'CZE',
      alternate_values: ['Česká republika', 'Česko', 'Czechia'],
      boost: 2.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    DK: {
      default: 'Denmark',
      cc2: 'DK',
      cc3: 'DNK',
      alternate_values: ['Danmark'],
      boost: 3,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    DJ: {
      default: 'Djibouti',
      cc2: 'DJ',
      cc3: 'DJI',
      alternate_values: ['Jībūtī', 'جيبوتي', 'Djibouti'],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    DM: {
      default: 'Dominica',
      cc2: 'DM',
      cc3: 'DMA',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    DO: {
      default: 'Dominican Republic',
      cc2: 'DO',
      cc3: 'DOM',
      alternate_values: ['República Dominicana'],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    EC: {
      default: 'Ecuador',
      cc2: 'EC',
      cc3: 'ECU',
      alternate_values: [],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    EG: {
      default: 'Egypt',
      cc2: 'EG',
      cc3: 'EGY',
      alternate_values: ['Misr', 'Masr', 'مصر'],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    SV: {
      default: 'El Salvador',
      cc2: 'SV',
      cc3: 'SLV',
      alternate_values: [],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    SX: {
      default: 'Sint Maarten',
      cc2: 'SX',
      cc3: 'SXM',
      alternate_values: [],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    GQ: {
      default: 'Equatorial Guinea',
      cc2: 'GQ',
      cc3: 'GNQ',
      alternate_values: ['Guinea Ecuatorial'],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    ER: {
      default: 'Eritrea',
      cc2: 'ER',
      cc3: 'ERI',
      alternate_values: ['Iritriya', 'إرتريا', 'Erta', 'ኤርትራ'],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    EE: {
      default: 'Estonia',
      cc2: 'EE',
      cc3: 'EST',
      alternate_values: ['Eesti'],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    ET: {
      default: 'Ethiopia',
      cc2: 'ET',
      cc3: 'ETH',
      alternate_values: ["Ityop'ia", 'ኢትዮጲያ', 'ኢትዮጵያ'],
      boost: 0.7,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    FK: {
      default: 'Falkland Islands (Malvinas)',
      cc2: 'FK',
      cc3: 'FLK',
      alternate_values: ['Islas Malvinas'],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    FO: {
      default: 'Faroe Islands',
      cc2: 'FO',
      cc3: 'FRO',
      alternate_values: ['Føroyar', 'Færøerne'],
      boost: 0.7,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    FJ: {
      default: 'Fiji',
      cc2: 'FJ',
      cc3: 'FJI',
      alternate_values: ['Viti', 'फ़िजी'],
      boost: 0.7,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    FI: {
      default: 'Finland',
      cc2: 'FI',
      cc3: 'FIN',
      alternate_values: ['Suomi'],
      boost: 3,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    FR: {
      default: 'France',
      cc2: 'FR',
      cc3: 'FRA',
      alternate_values: [],
      boost: 3.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    GF: {
      default: 'French Guiana',
      cc2: 'GF',
      cc3: 'GUF',
      alternate_values: ['Guyane'],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    PF: {
      default: 'French Polynesia',
      cc2: 'PF',
      cc3: 'PYF',
      alternate_values: ['Polynésie française'],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    TF: {
      default: 'French Southern Territories',
      cc2: 'TF',
      cc3: 'ATF',
      alternate_values: [
        'Terres australes et antarctiques françaises',
        'French Southern and Antarctic Lands',
      ],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    GA: {
      default: 'Gabon',
      cc2: 'GA',
      cc3: 'GAB',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    GM: {
      default: 'Gambia',
      cc2: 'GM',
      cc3: 'GMB',
      alternate_values: ['The Gambia'],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    GE: {
      default: 'Georgia',
      cc2: 'GE',
      cc3: 'GEO',
      alternate_values: ["Sak'art'velo", 'საქართველო'],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    DE: {
      default: 'Germany',
      cc2: 'DE',
      cc3: 'DEU',
      alternate_values: ['Deutschland'],
      boost: 4,
      has_regions: true,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    GH: {
      default: 'Ghana',
      cc2: 'GH',
      cc3: 'GHA',
      alternate_values: [],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    GI: {
      default: 'Gibraltar',
      cc2: 'GI',
      cc3: 'GIB',
      alternate_values: [],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    GR: {
      default: 'Greece',
      cc2: 'GR',
      cc3: 'GRC',
      alternate_values: ['Hellas', 'Ελλάς', 'Ellada', 'Ελλάδα'],
      boost: 2.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    GL: {
      default: 'Greenland',
      cc2: 'GL',
      cc3: 'GRL',
      alternate_values: ['Kalaallit Nunaat', 'Grønland'],
      boost: 0.7,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    GD: {
      default: 'Grenada',
      cc2: 'GD',
      cc3: 'GRD',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    GP: {
      default: 'Guadeloupe',
      cc2: 'GP',
      cc3: 'GLP',
      alternate_values: [],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    GU: {
      default: 'Guam',
      cc2: 'GU',
      cc3: 'GUM',
      alternate_values: [],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    GT: {
      default: 'Guatemala',
      cc2: 'GT',
      cc3: 'GTM',
      alternate_values: [],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    GG: {
      default: 'Guernsey',
      cc2: 'GG',
      cc3: 'GGY',
      alternate_values: [],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    GN: {
      default: 'Guinea',
      cc2: 'GN',
      cc3: 'GIN',
      alternate_values: ['Guinée', 'Gine'],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    GW: {
      default: 'Guinea-bissau',
      cc2: 'GW',
      cc3: 'GNB',
      alternate_values: ['Guiné-Bissau'],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    GY: {
      default: 'Guyana',
      cc2: 'GY',
      cc3: 'GUY',
      alternate_values: [],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    HT: {
      default: 'Haiti',
      cc2: 'HT',
      cc3: 'HTI',
      alternate_values: ['Haïti', 'Ayiti'],
      boost: 0.7,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    HM: {
      default: 'Heard Island and McDonald Island',
      cc2: 'HM',
      cc3: 'HMD',
      alternate_values: [],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    VA: {
      default: 'Holy See (Vatican City State)',
      cc2: 'VA',
      cc3: 'VAT',
      alternate_values: [],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    HN: {
      default: 'Honduras',
      cc2: 'HN',
      cc3: 'HND',
      alternate_values: [],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    HK: {
      default: 'Hong Kong',
      cc2: 'HK',
      cc3: 'HKG',
      alternate_values: [],
      boost: 3,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    HU: {
      default: 'Hungary',
      cc2: 'HU',
      cc3: 'HUN',
      alternate_values: ['Magyarország'],
      boost: 2.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    IS: {
      default: 'Iceland',
      cc2: 'IS',
      cc3: 'ISL',
      alternate_values: ['Ísland'],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    IN: {
      default: 'India',
      cc2: 'IN',
      cc3: 'IND',
      alternate_values: ['Bhārat', 'Hindustān', 'भारत', 'हिंदुस्तान'],
      boost: 3,
      has_regions: true,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    ID: {
      default: 'Indonesia',
      cc2: 'ID',
      cc3: 'IDN',
      alternate_values: [],
      boost: 3,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    IR: {
      default: 'Iran, Islamic Republic of',
      cc2: 'IR',
      cc3: 'IRN',
      alternate_values: ['Īrān', 'ایران'],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    IQ: {
      default: 'Iraq',
      cc2: 'IQ',
      cc3: 'IRQ',
      alternate_values: ["Al-'Iraq", 'العراق'],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    IE: {
      default: 'Ireland',
      cc2: 'IE',
      cc3: 'IRL',
      alternate_values: ['Éire'],
      boost: 3.5,
      has_regions: true,
      regions_required: true,
      regions_type: 'county',
      active: true,
    },
    IM: {
      default: 'Isle of Man',
      cc2: 'IM',
      cc3: 'IMN',
      alternate_values: ['Ellan Vannin'],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    IL: {
      default: 'Israel',
      cc2: 'IL',
      cc3: 'ISR',
      alternate_values: ['Yisrael', 'ישראל', "Isrā'īl", 'إسرائيل'],
      boost: 2.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    IT: {
      default: 'Italy',
      cc2: 'IT',
      cc3: 'ITA',
      alternate_values: ['Italia'],
      boost: 3.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    JM: {
      default: 'Jamaica',
      cc2: 'JM',
      cc3: 'JAM',
      alternate_values: [],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    JP: {
      default: 'Japan',
      cc2: 'JP',
      cc3: 'JPN',
      alternate_values: ['Nippon', 'Nihon', '日本'],
      boost: 3,
      has_regions: true,
      regions_required: true,
      regions_type: 'prefecture',
      active: true,
    },
    JE: {
      default: 'Jersey',
      cc2: 'JE',
      cc3: 'JEY',
      alternate_values: ['Jèrri'],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    JO: {
      default: 'Jordan',
      cc2: 'JO',
      cc3: 'JOR',
      alternate_values: ['Al-’Urdun', 'الأردن'],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    KZ: {
      default: 'Kazakhstan',
      cc2: 'KZ',
      cc3: 'KAZ',
      alternate_values: ['Qazaqstan', 'Қазақстан', 'Kazakhstán', 'Казахстан'],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    KE: {
      default: 'Kenya',
      cc2: 'KE',
      cc3: 'KEN',
      alternate_values: [],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    KI: {
      default: 'Kiribati',
      cc2: 'KI',
      cc3: 'KIR',
      alternate_values: [],
      boost: 0.7,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    KP: {
      default: "Korea, Democratic People's Republic of",
      cc2: 'KP',
      cc3: 'PRK',
      alternate_values: ['Chosŏn', 'North Korea', 'Bukchosŏn', '조선', '朝鮮'],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    KR: {
      default: 'Korea, Republic of',
      cc2: 'KR',
      cc3: 'KOR',
      alternate_values: ['Hanguk', 'South Korea', 'Namhan', '한국', '韓國'],
      boost: 2.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    KW: {
      default: 'Kuwait',
      cc2: 'KW',
      cc3: 'KWT',
      alternate_values: ['Al-Kuwayt', 'الكويت'],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    KG: {
      default: 'Kyrgyzstan',
      cc2: 'KG',
      cc3: 'KGZ',
      alternate_values: ['Кыргызстан', 'Kirgizija', 'Киргизия'],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    LA: {
      default: "Lao People's Democratic Republic",
      cc2: 'LA',
      cc3: 'LAO',
      alternate_values: ['ລາວ', 'Laos'],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    LV: {
      default: 'Latvia',
      cc2: 'LV',
      cc3: 'LVA',
      alternate_values: ['Latvija'],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    LB: {
      default: 'Lebanon',
      cc2: 'LB',
      cc3: 'LBN',
      alternate_values: ['Lubnān', 'لبنان'],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    LS: {
      default: 'Lesotho',
      cc2: 'LS',
      cc3: 'LSO',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    LR: {
      default: 'Liberia',
      cc2: 'LR',
      cc3: 'LBR',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    LY: {
      default: 'Libya',
      cc2: 'LY',
      cc3: 'LBY',
      alternate_values: ['Lībiyā', 'ليبيا'],
      boost: 0.7,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    LI: {
      default: 'Liechtenstein',
      cc2: 'LI',
      cc3: 'LIE',
      alternate_values: [],
      boost: 0.7,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    LT: {
      default: 'Lithuania',
      cc2: 'LT',
      cc3: 'LTU',
      alternate_values: ['Lietuva'],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    LU: {
      default: 'Luxembourg',
      cc2: 'LU',
      cc3: 'LUX',
      alternate_values: ['Lëtzebuerg', 'Luxemburg'],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    MO: {
      default: 'Macau Special Administrative Region of China',
      cc2: 'MO',
      cc3: 'MAC',
      alternate_values: [],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    MK: {
      default: 'North Macedonia',
      cc2: 'MK',
      cc3: 'MKD',
      alternate_values: ['Severna Makedonija', 'Северна Македонија'],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    MG: {
      default: 'Madagascar',
      cc2: 'MG',
      cc3: 'MDG',
      alternate_values: ['Madagasikara'],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    MW: {
      default: 'Malawi',
      cc2: 'MW',
      cc3: 'MWI',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    MY: {
      default: 'Malaysia',
      cc2: 'MY',
      cc3: 'MYS',
      alternate_values: [],
      boost: 3,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    MV: {
      default: 'Maldives',
      cc2: 'MV',
      cc3: 'MDV',
      alternate_values: ['Dhivehi Raajje', 'ދިވެހިރާއްޖެ'],
      boost: 0.7,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    ML: {
      default: 'Mali',
      cc2: 'ML',
      cc3: 'MLI',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    MT: {
      default: 'Malta',
      cc2: 'MT',
      cc3: 'MLT',
      alternate_values: [],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    MH: {
      default: 'Marshall Islands',
      cc2: 'MH',
      cc3: 'MHL',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    MQ: {
      default: 'Martinique',
      cc2: 'MQ',
      cc3: 'MTQ',
      alternate_values: [],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    MR: {
      default: 'Mauritania',
      cc2: 'MR',
      cc3: 'MRT',
      alternate_values: ['Mauritanie', 'Mūrītāniyā', 'موريتانيا'],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    MU: {
      default: 'Mauritius',
      cc2: 'MU',
      cc3: 'MUS',
      alternate_values: ['Maurice'],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    YT: {
      default: 'Mayotte',
      cc2: 'YT',
      cc3: 'MYT',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    MX: {
      default: 'Mexico',
      cc2: 'MX',
      cc3: 'MEX',
      alternate_values: ['México'],
      boost: 3,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    FM: {
      default: 'Micronesia, Federated States of',
      cc2: 'FM',
      cc3: 'FSM',
      alternate_values: [],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    MD: {
      default: 'Moldova, Republic of',
      cc2: 'MD',
      cc3: 'MDA',
      alternate_values: [],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    MC: {
      default: 'Monaco',
      cc2: 'MC',
      cc3: 'MCO',
      alternate_values: [],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    MN: {
      default: 'Mongolia',
      cc2: 'MN',
      cc3: 'MNG',
      alternate_values: ['Mongol Uls', 'Монгол Улс'],
      boost: 0.7,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    ME: {
      default: 'Montenegro',
      cc2: 'ME',
      cc3: 'MNE',
      alternate_values: ['Crna Gora', 'Црна Гора'],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    MS: {
      default: 'Montserrat',
      cc2: 'MS',
      cc3: 'MSR',
      alternate_values: [],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    MA: {
      default: 'Morocco',
      cc2: 'MA',
      cc3: 'MAR',
      alternate_values: ['Al-Maghrib', 'المغرب'],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    MZ: {
      default: 'Mozambique',
      cc2: 'MZ',
      cc3: 'MOZ',
      alternate_values: ['Moçambique'],
      boost: 0.7,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    MM: {
      default: 'Myanmar',
      cc2: 'MM',
      cc3: 'MMR',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    NA: {
      default: 'Namibia',
      cc2: 'NA',
      cc3: 'NAM',
      alternate_values: [],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    NR: {
      default: 'Nauru',
      cc2: 'NR',
      cc3: 'NRU',
      alternate_values: ['Naoero', 'Nauruo'],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    NP: {
      default: 'Nepal',
      cc2: 'NP',
      cc3: 'NPL',
      alternate_values: ['Nepāla', 'नेपाल'],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    NL: {
      default: 'Netherlands',
      cc2: 'NL',
      cc3: 'NLD',
      alternate_values: ['Nederland'],
      boost: 3.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'province',
      active: true,
    },
    NC: {
      default: 'New Caledonia',
      cc2: 'NC',
      cc3: 'NCL',
      alternate_values: ['Nouvelle-Calédonie'],
      boost: 0.7,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    NZ: {
      default: 'New Zealand',
      cc2: 'NZ',
      cc3: 'NZL',
      alternate_values: ['Aotearoa'],
      boost: 3.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    NI: {
      default: 'Nicaragua',
      cc2: 'NI',
      cc3: 'NIC',
      alternate_values: [],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    NE: {
      default: 'Niger',
      cc2: 'NE',
      cc3: 'NER',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    NG: {
      default: 'Nigeria',
      cc2: 'NG',
      cc3: 'NGA',
      alternate_values: [],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    NU: {
      default: 'Niue',
      cc2: 'NU',
      cc3: 'NIU',
      alternate_values: ['Niuē'],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    NF: {
      default: 'Norfolk Island',
      cc2: 'NF',
      cc3: 'NFK',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    MP: {
      default: 'Northern Mariana Islands',
      cc2: 'MP',
      cc3: 'MNP',
      alternate_values: [],
      boost: 0.7,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    NO: {
      default: 'Norway',
      cc2: 'NO',
      cc3: 'NOR',
      alternate_values: ['Norge', 'Noreg'],
      boost: 3.5,
      has_regions: true,
      regions_required: false,
      regions_type: 'county',
      active: true,
    },
    OM: {
      default: 'Oman',
      cc2: 'OM',
      cc3: 'OMN',
      alternate_values: ['‘Umān', 'عُمان'],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    PK: {
      default: 'Pakistan',
      cc2: 'PK',
      cc3: 'PAK',
      alternate_values: ['Pākistān', 'پاکستان'],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'province',
      active: true,
    },
    PW: {
      default: 'Palau',
      cc2: 'PW',
      cc3: 'PLW',
      alternate_values: ['Belau'],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    PS: {
      default: 'Palestine, State of',
      cc2: 'PS',
      cc3: 'PSE',
      alternate_values: ['Filastīn', 'Dawlat Filasţīn', 'فلسطين', 'دولة فلسطين'],
      boost: 0.7,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    PA: {
      default: 'Panama',
      cc2: 'PA',
      cc3: 'PAN',
      alternate_values: ['Panamá'],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    PG: {
      default: 'Papua New Guinea',
      cc2: 'PG',
      cc3: 'PNG',
      alternate_values: ['Papua Niugini'],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    PY: {
      default: 'Paraguay',
      cc2: 'PY',
      cc3: 'PRY',
      alternate_values: ['Paraguái'],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    PE: {
      default: 'Peru',
      cc2: 'PE',
      cc3: 'PER',
      alternate_values: ['Perú'],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    PH: {
      default: 'Philippines',
      cc2: 'PH',
      cc3: 'PHL',
      alternate_values: ['Pilipinas', 'Filipinas'],
      boost: 3,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    PN: {
      default: 'Pitcairn',
      cc2: 'PN',
      cc3: 'PCN',
      alternate_values: ['Pitcairn Islands'],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    PL: {
      default: 'Poland',
      cc2: 'PL',
      cc3: 'POL',
      alternate_values: ['Polska'],
      boost: 2.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    PT: {
      default: 'Portugal',
      cc2: 'PT',
      cc3: 'PRT',
      alternate_values: ['Portugal'],
      boost: 2.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    PR: {
      default: 'Puerto Rico',
      cc2: 'PR',
      cc3: 'PRI',
      alternate_values: [],
      boost: 2.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    QA: {
      default: 'Qatar',
      cc2: 'QA',
      cc3: 'QAT',
      alternate_values: ['قطر'],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    RE: {
      default: 'Réunion',
      cc2: 'RE',
      cc3: 'REU',
      alternate_values: ['Reunion', 'La Réunion'],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    RO: {
      default: 'Romania',
      cc2: 'RO',
      cc3: 'ROU',
      alternate_values: ['România'],
      boost: 2.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    RU: {
      default: 'Russian Federation',
      cc2: 'RU',
      cc3: 'RUS',
      alternate_values: ['Rossiya', 'Rossiâ', 'Россия'],
      boost: 3,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    RW: {
      default: 'Rwanda',
      cc2: 'RW',
      cc3: 'RWA',
      alternate_values: [],
      boost: 0.7,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    BL: {
      default: 'Saint Barthélemy',
      cc2: 'BL',
      cc3: 'BLM',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    SH: {
      default: 'Saint Helena, Ascension and Tristan da Cunha',
      cc2: 'SH',
      cc3: 'SHN',
      alternate_values: ['Saint Helena', 'Ascension', 'Tristan da Cunha'],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    KN: {
      default: 'Saint Kitts and Nevis',
      cc2: 'KN',
      cc3: 'KNA',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    LC: {
      default: 'Saint Lucia',
      cc2: 'LC',
      cc3: 'LCA',
      alternate_values: [],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    MF: {
      default: 'Saint Martin',
      cc2: 'MF',
      cc3: 'MAF',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    PM: {
      default: 'Saint Pierre and Miquelon',
      cc2: 'PM',
      cc3: 'SPM',
      alternate_values: ['Saint-Pierre et Miquelon'],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    VC: {
      default: 'Saint Vincent and the Grenadines',
      cc2: 'VC',
      cc3: 'VCT',
      alternate_values: [],
      boost: 0.7,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    WS: {
      default: 'Samoa',
      cc2: 'WS',
      cc3: 'WSM',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    SM: {
      default: 'San Marino',
      cc2: 'SM',
      cc3: 'SMR',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    SS: {
      default: 'South Sudan',
      cc2: 'SS',
      cc3: 'SSD',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    ST: {
      default: 'Sao Tome and Principe',
      cc2: 'ST',
      cc3: 'STP',
      alternate_values: ['São Tomé e Príncipe'],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    SA: {
      default: 'Saudi Arabia',
      cc2: 'SA',
      cc3: 'SAU',
      alternate_values: ['Al-Mamlaka Al-‘Arabiyyah as Sa‘ūdiyyah', 'المملكة العربية السعودية'],
      boost: 2.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    SN: {
      default: 'Senegal',
      cc2: 'SN',
      cc3: 'SEN',
      alternate_values: ['Sénégal'],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    RS: {
      default: 'Serbia',
      cc2: 'RS',
      cc3: 'SRB',
      alternate_values: ['Srbija', 'Србија'],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    SC: {
      default: 'Seychelles',
      cc2: 'SC',
      cc3: 'SYC',
      alternate_values: ['Sesel'],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    SL: {
      default: 'Sierra Leone',
      cc2: 'SL',
      cc3: 'SLE',
      alternate_values: [],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    SG: {
      default: 'Singapore',
      cc2: 'SG',
      cc3: 'SGP',
      alternate_values: ['Singapura', 'Xīnjiāpō', '新加坡', 'Singapur', 'சிங்கப்பூர்'],
      boost: 3,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    SK: {
      default: 'Slovakia',
      cc2: 'SK',
      cc3: 'SVK',
      alternate_values: ['Slovensko'],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    SI: {
      default: 'Slovenia',
      cc2: 'SI',
      cc3: 'SVN',
      alternate_values: ['Slovenija'],
      boost: 2.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    SB: {
      default: 'Solomon Islands',
      cc2: 'SB',
      cc3: 'SLB',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    SO: {
      default: 'Somalia',
      cc2: 'SO',
      cc3: 'SOM',
      alternate_values: ['Soomaaliya', 'aş-Şūmāl', 'الصومال'],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    ZA: {
      default: 'South Africa',
      cc2: 'ZA',
      cc3: 'ZAF',
      alternate_values: [
        'Suid-Afrika',
        'iNingizimu Afrika',
        'uMzantsi Afrika',
        'Afrika-Borwa',
        'Afrika Borwa',
        'Aforika Borwa',
        'Afurika Tshipembe',
        'Afrika Dzonga',
        'iSewula Afrika',
      ],
      boost: 3,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    GS: {
      default: 'South Georgia and the South Sandwich Islands',
      cc2: 'GS',
      cc3: 'SGS',
      alternate_values: [],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    ES: {
      default: 'Spain',
      cc2: 'ES',
      cc3: 'ESP',
      alternate_values: ['España', 'Espanya', 'Espainia', 'Espanha'],
      boost: 3,
      has_regions: true,
      regions_required: true,
      regions_type: 'province',
      active: true,
    },
    LK: {
      default: 'Sri Lanka',
      cc2: 'LK',
      cc3: 'LKA',
      alternate_values: ['Sri Lankā', 'ශ්‍රී ලංකාව', 'ஸ்ரீ லங்க'],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    SD: {
      default: 'Sudan',
      cc2: 'SD',
      cc3: 'SDN',
      alternate_values: ['As-Sudan', 'السودان'],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    SR: {
      default: 'Suriname',
      cc2: 'SR',
      cc3: 'SUR',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    SJ: {
      default: 'Svalbard and Jan Mayen',
      cc2: 'SJ',
      cc3: 'SJM',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    SZ: {
      default: 'Eswatini',
      cc2: 'SZ',
      cc3: 'SWZ',
      alternate_values: ['Swaziland'],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    SE: {
      default: 'Sweden',
      cc2: 'SE',
      cc3: 'SWE',
      alternate_values: ['Sverige'],
      boost: 3,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    CH: {
      default: 'Switzerland',
      cc2: 'CH',
      cc3: 'CHE',
      alternate_values: ['Schweiz', 'Suisse', 'Svizzera', 'Svizra'],
      boost: 3.5,
      has_regions: true,
      regions_required: false,
      regions_type: 'canton',
      active: true,
    },
    SY: {
      default: 'Syrian Arab Republic',
      cc2: 'SY',
      cc3: 'SYR',
      alternate_values: ['Suriyah', 'سورية'],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    TW: {
      default: 'Taiwan',
      cc2: 'TW',
      cc3: 'TWN',
      alternate_values: ['Zhōnghuá Mínguó', 'Táiwan', '中華民國', '臺灣/台灣'],
      boost: 2.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    TJ: {
      default: 'Tajikistan',
      cc2: 'TJ',
      cc3: 'TJK',
      alternate_values: ['Tojikistan', 'Тоҷикистон'],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    TZ: {
      default: 'Tanzania, United Republic of',
      cc2: 'TZ',
      cc3: 'TZA',
      alternate_values: [],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    TH: {
      default: 'Thailand',
      cc2: 'TH',
      cc3: 'THA',
      alternate_values: ['Mueang Thai', 'Prathet Thai', 'Ratcha-anachak Thai'],
      boost: 3,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    TL: {
      default: 'Timor-Leste',
      cc2: 'TL',
      cc3: 'TLS',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    TG: {
      default: 'Togo',
      cc2: 'TG',
      cc3: 'TGO',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    TK: {
      default: 'Tokelau',
      cc2: 'TK',
      cc3: 'TKL',
      alternate_values: [],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    TO: {
      default: 'Tonga',
      cc2: 'TO',
      cc3: 'TON',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    TT: {
      default: 'Trinidad and Tobago',
      cc2: 'TT',
      cc3: 'TTO',
      alternate_values: [],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    TN: {
      default: 'Tunisia',
      cc2: 'TN',
      cc3: 'TUN',
      alternate_values: ['Tunis'],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    TR: {
      default: 'Turkey',
      cc2: 'TR',
      cc3: 'TUR',
      alternate_values: ['Türkiye'],
      boost: 3,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    TM: {
      default: 'Turkmenistan',
      cc2: 'TM',
      cc3: 'TKM',
      alternate_values: ['Türkmenistan'],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    TC: {
      default: 'Turks and Caicos Islands',
      cc2: 'TC',
      cc3: 'TCA',
      alternate_values: [],
      boost: 0.7,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    TV: {
      default: 'Tuvalu',
      cc2: 'TV',
      cc3: 'TUV',
      alternate_values: [],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    UG: {
      default: 'Uganda',
      cc2: 'UG',
      cc3: 'UGA',
      alternate_values: [],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    UA: {
      default: 'Ukraine',
      cc2: 'UA',
      cc3: 'UKR',
      alternate_values: ['Ukraїna'],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    AE: {
      default: 'United Arab Emirates',
      cc2: 'AE',
      cc3: 'ARE',
      alternate_values: ['Al-’Imārat Al-‘Arabiyyah Al-Muttaḥidah'],
      boost: 3,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    GB: {
      default: 'United Kingdom',
      cc2: 'GB',
      cc3: 'GBR',
      alternate_values: ['Great Britain', 'England', 'Northern Ireland', 'Britain', 'UK'],
      boost: 4,
      has_regions: false,
      regions_required: false,
      regions_type: 'county',
      active: true,
    },
    US: {
      default: 'United States',
      cc2: 'US',
      cc3: 'USA',
      alternate_values: ['USA', 'United States of America', 'America'],
      boost: 4.5,
      has_regions: true,
      regions_required: true,
      regions_type: 'state',
      active: true,
    },
    UM: {
      default: 'United States Minor Outlying Islands',
      cc2: 'UM',
      cc3: 'UMI',
      alternate_values: [],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    UY: {
      default: 'Uruguay',
      cc2: 'UY',
      cc3: 'URY',
      alternate_values: ['República Oriental del Uruguay'],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    UZ: {
      default: 'Uzbekistan',
      cc2: 'UZ',
      cc3: 'UZB',
      alternate_values: ["O'zbekiston"],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    VU: {
      default: 'Vanuatu',
      cc2: 'VU',
      cc3: 'VUT',
      alternate_values: [],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    VE: {
      default: 'Venezuela',
      cc2: 'VE',
      cc3: 'VEN',
      alternate_values: ['Venezuela, Bolivarian Republic of', 'República Bolivariana de Venezuela'],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    VN: {
      default: 'Vietnam',
      cc2: 'VN',
      cc3: 'VNM',
      alternate_values: ['Việt Nam'],
      boost: 2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    VG: {
      default: 'Virgin Islands, British',
      cc2: 'VG',
      cc3: 'VGB',
      alternate_values: [],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    VI: {
      default: 'Virgin Islands, U.S.',
      cc2: 'VI',
      cc3: 'VIR',
      alternate_values: [],
      boost: 1.5,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    WF: {
      default: 'Wallis and Futuna Islands',
      cc2: 'WF',
      cc3: 'WLF',
      alternate_values: ['Wallis-et-Futuna'],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    EH: {
      default: 'Western Sahara',
      cc2: 'EH',
      cc3: 'ESH',
      alternate_values: [],
      boost: 0.2,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    YE: {
      default: 'Yemen',
      cc2: 'YE',
      cc3: 'YEM',
      alternate_values: ['Al-Yaman'],
      boost: 0.4,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    ZM: {
      default: 'Zambia',
      cc2: 'ZM',
      cc3: 'ZMB',
      alternate_values: [],
      boost: 1,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
    ZW: {
      default: 'Zimbabwe',
      cc2: 'ZW',
      cc3: 'ZWE',
      alternate_values: [],
      boost: 0.7,
      has_regions: false,
      regions_required: false,
      regions_type: 'state',
      active: true,
    },
  },
};
