export const CARD_TYPES = new Set(["new-card", "saved-card", "card"]);

export const BUTTON_CLICK_HINT_OPTION_TYPES = new Set([
  "apple-pay",
  "google-pay",
  "paypal",
  "paypal-pay-later",
  "paypal-credit",
  "venmo",
  "sepa",
  "bancontact",
  "eps",
  "blik",
  "ideal",
  "przelewy24",
  "generic",
]);

export const PURCHASE_ORDER_MAX_LENGTH = 32;

export const GATEWAY_NAME_BY_TYPE: Record<string, string> = {
  // Synced with foxy-sdk checkout PaymentOption gateway types.
  accept_blue: "Accept.blue",
  authorize: "Authorize.NET",
  authorize_cim: "Authorize.NET CIM",
  bambora: "Bambora",
  barclaycard: "Barclaycard",
  beanstream: "Beanstream",
  bluefin: "Bluefin",
  bluepay: "BluePay",
  braintree: "Braintree",
  cardpointe: "CardPointe",
  datacash: "DataCash",
  digitalriver: "Digital River",
  durango: "Durango",
  ems_pay: "EMS Pay",
  epicor_esdm_token: "Epicor ESDM Token",
  eprocessingnetwork: "eProcessingNetwork",
  eway: "eWAY",
  fatzebra: "Fat Zebra",
  firstdata: "First Data",
  firstdata_e4: "First Data E4",
  fosdick: "Fosdick",
  goemerchant: "goEmerchant",
  handepay: "Handepay",
  helcim: "Helcim",
  helcim_commerce: "Helcim Commerce",
  inspire: "Inspire",
  litle: "Litle",
  lucy: "Lucy",
  merchantesolutions: "Merchant e-Solutions",
  migs_anz_egate: "MIGS ANZ eGate",
  migs_commweb: "MIGS CommWeb",
  moneris: "Moneris",
  netbilling: "Netbilling",
  nmi: "NMI",
  nmi_native: "NMI Native",
  orbital_salem: "Orbital Salem",
  orbital_tampa: "Orbital Tampa",
  paperless: "Paperless",
  pawapay: "PawaPay",
  payconex: "PayConex",
  payflowpro: "Payflow Pro",
  paygate: "PayGate",
  payjunction: "PayJunction",
  payleap: "PayLeap",
  payline: "Payline",
  paylinedata: "Payline Data",
  paymentexpress: "Payment Express",
  paymentsense: "Paymentsense",
  paypoint_enterprise: "PayPoint Enterprise",
  paypoint_gateway: "PayPoint Gateway",
  paypoint_metacharge: "PayPoint MetaCharge",
  paytrace: "PayTrace",
  payvector: "PayVector",
  plugnpay: "PlugnPay",
  plugnpay_authnet: "PlugnPay AuthNet",
  propay: "ProPay",
  quantumgateway: "Quantum Gateway",
  quickbook_payments: "QuickBooks Payments",
  quickbooks: "QuickBooks",
  realex: "Realex",
  sagepayments: "Sage Payments",
  securenet: "SecureNet",
  stripe: "Stripe",
  stripe_omnipay: "Stripe OmniPay",
  totalapps: "Total Apps",
  transaction_express: "Transaction Express",
  transfirst: "TransFirst",
  usaepay: "USAePay",
  vanco: "Vanco",
  vantiv_omnipay: "Vantiv OmniPay",
  virtualmerchant: "Virtual Merchant",
  wallee: "Wallee",
  wepay: "WePay",
  westpac: "Westpac",
  xendit: "Xendit",
  accept_blue_ach: "Accept.blue ACH",
  authorize_ach: "Authorize.NET ACH",
  paperless_ach: "Paperless ACH",
  payjunction_ach: "PayJunction ACH",
  vantiv_ach: "Vantiv ACH",
  adyen: "Adyen",
  amazon_fps: "Amazon FPS",
  bitpay: "BitPay",
  cardx: "CardX",
  ccavenue: "CCAvenue",
  coinbase: "Coinbase",
  coinbase_v2: "Coinbase v2",
  comgate: "Comgate",
  curbstone: "Curbstone",
  cybersource_pos: "Cybersource POS",
  cybersource_sa_web: "Cybersource SA Web",
  dibs: "DIBS",
  dwolla: "Dwolla",
  epayments: "ePayments",
  mercadopago: "Mercado Pago",
  migs: "MIGS",
  mollie_omnipay: "Mollie OmniPay",
  ogone: "Ogone",
  paymentexpress_ws: "Payment Express WS",
  payu_omnipay: "PayU OmniPay",
  pesapal: "Pesapal",
  skrill: "Skrill",
  smartscreen: "SmartScreen",
  tazapay: "Tazapay",
  trustcommerce: "TrustCommerce",
  twocheckout: "2Checkout",
  vivawallet_checkout: "Viva Wallet Checkout",
  wigwag: "WigWag",
  worldline_hosted: "Worldline Hosted",
  worldpay_online: "Worldpay Online",
  stripe_connect: "Stripe Connect",
  stripe_connect_charge: "Stripe Connect Charge",
  stripe_v2: "Stripe",
  paypal_platform: "PayPal",
  klarna: "Klarna",
};

export const FIELD_STYLE_PROBE_CLASS_NAME =
  "h-8 px-2.5 py-1 text-base font-normal md:text-sm border border-transparent bg-card text-foreground placeholder:text-muted-foreground";
