export type Region = { code: string; name: string };
export type Country = { code: string; name: string; regions: Region[] };

export const COUNTRIES: Country[] = [
  {
    code: "AF",
    name: "Afghanistan",
    regions: [],
  },
  {
    code: "AX",
    name: "Åland Islands",
    regions: [],
  },
  {
    code: "AL",
    name: "Albania",
    regions: [],
  },
  {
    code: "DZ",
    name: "Algeria",
    regions: [],
  },
  {
    code: "AS",
    name: "American Samoa",
    regions: [],
  },
  {
    code: "AD",
    name: "Andorra",
    regions: [],
  },
  {
    code: "AO",
    name: "Angola",
    regions: [],
  },
  {
    code: "AI",
    name: "Anguilla",
    regions: [],
  },
  {
    code: "AQ",
    name: "Antarctica",
    regions: [],
  },
  {
    code: "AG",
    name: "Antigua and Barbuda",
    regions: [],
  },
  {
    code: "AR",
    name: "Argentina",
    regions: [],
  },
  {
    code: "AM",
    name: "Armenia",
    regions: [],
  },
  {
    code: "AW",
    name: "Aruba",
    regions: [],
  },
  {
    code: "AU",
    name: "Australia",
    regions: [
      { code: "ACT", name: "Australian Capital Territory" },
      { code: "NSW", name: "New South Wales" },
      { code: "NT", name: "Northern Territory" },
      { code: "QLD", name: "Queensland" },
      { code: "SA", name: "South Australia" },
      { code: "TAS", name: "Tasmania" },
      { code: "VIC", name: "Victoria" },
      { code: "WA", name: "Western Australia" },
    ],
  },
  {
    code: "AT",
    name: "Austria",
    regions: [
      { code: "BL", name: "Burgenland" },
      { code: "KN", name: "Kaernten" },
      { code: "NO", name: "Niederoesterreich" },
      { code: "OO", name: "Oberoesterreich" },
      { code: "SB", name: "Salzburg" },
      { code: "ST", name: "Steiermark" },
      { code: "TI", name: "Tirol" },
      { code: "VB", name: "Voralberg" },
      { code: "WI", name: "Wien" },
    ],
  },
  {
    code: "AZ",
    name: "Azerbaijan",
    regions: [],
  },
  {
    code: "BS",
    name: "Bahamas",
    regions: [],
  },
  {
    code: "BH",
    name: "Bahrain",
    regions: [],
  },
  {
    code: "BD",
    name: "Bangladesh",
    regions: [],
  },
  {
    code: "BB",
    name: "Barbados",
    regions: [],
  },
  {
    code: "BY",
    name: "Belarus",
    regions: [],
  },
  {
    code: "BE",
    name: "Belgium",
    regions: [],
  },
  {
    code: "BZ",
    name: "Belize",
    regions: [],
  },
  {
    code: "BJ",
    name: "Benin",
    regions: [],
  },
  {
    code: "BM",
    name: "Bermuda",
    regions: [],
  },
  {
    code: "BT",
    name: "Bhutan",
    regions: [],
  },
  {
    code: "BO",
    name: "Bolivia",
    regions: [],
  },
  {
    code: "BQ",
    name: "Bonaire, Sint Eustatius and Saba",
    regions: [
      { code: "BO", name: "Bonaire" },
      { code: "SA", name: "Saba" },
      { code: "SE", name: "Sint Eustatius" },
    ],
  },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    regions: [],
  },
  {
    code: "BW",
    name: "Botswana",
    regions: [],
  },
  {
    code: "BV",
    name: "Bouvet Island",
    regions: [],
  },
  {
    code: "BR",
    name: "Brazil",
    regions: [],
  },
  {
    code: "IO",
    name: "British Indian Ocean Territory",
    regions: [],
  },
  {
    code: "BN",
    name: "Brunei Darussalam",
    regions: [],
  },
  {
    code: "BG",
    name: "Bulgaria",
    regions: [],
  },
  {
    code: "BF",
    name: "Burkina Faso",
    regions: [],
  },
  {
    code: "BI",
    name: "Burundi",
    regions: [],
  },
  {
    code: "KH",
    name: "Cambodia",
    regions: [],
  },
  {
    code: "CM",
    name: "Cameroon",
    regions: [],
  },
  {
    code: "CA",
    name: "Canada",
    regions: [
      { code: "AB", name: "Alberta" },
      { code: "BC", name: "British Columbia" },
      { code: "MB", name: "Manitoba" },
      { code: "NB", name: "New Brunswick" },
      { code: "NL", name: "Newfoundland and Labrador" },
      { code: "NT", name: "Northwest Territories" },
      { code: "NS", name: "Nova Scotia" },
      { code: "NU", name: "Nunavut" },
      { code: "ON", name: "Ontario" },
      { code: "PE", name: "Prince Edward Island" },
      { code: "QC", name: "Quebec" },
      { code: "SK", name: "Saskatchewan" },
      { code: "YT", name: "Yukon" },
    ],
  },
  {
    code: "CV",
    name: "Cape Verde",
    regions: [],
  },
  {
    code: "KY",
    name: "Cayman Islands",
    regions: [],
  },
  {
    code: "CF",
    name: "Central African Republic",
    regions: [],
  },
  {
    code: "TD",
    name: "Chad",
    regions: [],
  },
  {
    code: "CL",
    name: "Chile",
    regions: [],
  },
  {
    code: "CN",
    name: "China",
    regions: [],
  },
  {
    code: "CX",
    name: "Christmas Island",
    regions: [],
  },
  {
    code: "CC",
    name: "Cocos (Keeling) Islands",
    regions: [],
  },
  {
    code: "CO",
    name: "Colombia",
    regions: [],
  },
  {
    code: "KM",
    name: "Comoros",
    regions: [],
  },
  {
    code: "CG",
    name: "Congo",
    regions: [],
  },
  {
    code: "CD",
    name: "Congo, the Democratic Republic of the",
    regions: [],
  },
  {
    code: "CK",
    name: "Cook Islands",
    regions: [],
  },
  {
    code: "CR",
    name: "Costa Rica",
    regions: [],
  },
  {
    code: "CI",
    name: "Cote DIvoire",
    regions: [],
  },
  {
    code: "HR",
    name: "Croatia",
    regions: [],
  },
  {
    code: "CU",
    name: "Cuba",
    regions: [],
  },
  {
    code: "CW",
    name: "Curaçao",
    regions: [],
  },
  {
    code: "CY",
    name: "Cyprus",
    regions: [],
  },
  {
    code: "CZ",
    name: "Czech Republic",
    regions: [],
  },
  {
    code: "DK",
    name: "Denmark",
    regions: [],
  },
  {
    code: "DJ",
    name: "Djibouti",
    regions: [],
  },
  {
    code: "DM",
    name: "Dominica",
    regions: [],
  },
  {
    code: "DO",
    name: "Dominican Republic",
    regions: [],
  },
  {
    code: "EC",
    name: "Ecuador",
    regions: [],
  },
  {
    code: "EG",
    name: "Egypt",
    regions: [],
  },
  {
    code: "SV",
    name: "El Salvador",
    regions: [],
  },
  {
    code: "GQ",
    name: "Equatorial Guinea",
    regions: [],
  },
  {
    code: "ER",
    name: "Eritrea",
    regions: [],
  },
  {
    code: "EE",
    name: "Estonia",
    regions: [],
  },
  {
    code: "SZ",
    name: "Eswatini",
    regions: [],
  },
  {
    code: "ET",
    name: "Ethiopia",
    regions: [],
  },
  {
    code: "FK",
    name: "Falkland Islands (Malvinas)",
    regions: [],
  },
  {
    code: "FO",
    name: "Faroe Islands",
    regions: [],
  },
  {
    code: "FJ",
    name: "Fiji",
    regions: [],
  },
  {
    code: "FI",
    name: "Finland",
    regions: [],
  },
  {
    code: "FR",
    name: "France",
    regions: [],
  },
  {
    code: "GF",
    name: "French Guiana",
    regions: [],
  },
  {
    code: "PF",
    name: "French Polynesia",
    regions: [],
  },
  {
    code: "TF",
    name: "French Southern Territories",
    regions: [],
  },
  {
    code: "GA",
    name: "Gabon",
    regions: [],
  },
  {
    code: "GM",
    name: "Gambia",
    regions: [],
  },
  {
    code: "GE",
    name: "Georgia",
    regions: [],
  },
  {
    code: "DE",
    name: "Germany",
    regions: [
      { code: "BW", name: "Baden-Wuerttemberg" },
      { code: "BY", name: "Bayern" },
      { code: "BE", name: "Berlin" },
      { code: "BB", name: "Brandenburg" },
      { code: "HB", name: "Bremen" },
      { code: "HH", name: "Hamburg" },
      { code: "HE", name: "Hessen" },
      { code: "MV", name: "Mecklenburg-Vorpommern" },
      { code: "NI", name: "Niedersachsen" },
      { code: "NW", name: "Nordrhein-Westfalen" },
      { code: "RP", name: "Rheinland-Pfalz" },
      { code: "SL", name: "Saarland" },
      { code: "SN", name: "Sachsen" },
      { code: "ST", name: "Sachsen-Anhalt" },
      { code: "SH", name: "Schleswig-Holstein" },
      { code: "TH", name: "Thueringen" },
    ],
  },
  {
    code: "GH",
    name: "Ghana",
    regions: [],
  },
  {
    code: "GI",
    name: "Gibraltar",
    regions: [],
  },
  {
    code: "GR",
    name: "Greece",
    regions: [],
  },
  {
    code: "GL",
    name: "Greenland",
    regions: [],
  },
  {
    code: "GD",
    name: "Grenada",
    regions: [],
  },
  {
    code: "GP",
    name: "Guadeloupe",
    regions: [],
  },
  {
    code: "GU",
    name: "Guam",
    regions: [],
  },
  {
    code: "GT",
    name: "Guatemala",
    regions: [],
  },
  {
    code: "GG",
    name: "Guernsey",
    regions: [],
  },
  {
    code: "GN",
    name: "Guinea",
    regions: [],
  },
  {
    code: "GW",
    name: "Guinea-bissau",
    regions: [],
  },
  {
    code: "GY",
    name: "Guyana",
    regions: [],
  },
  {
    code: "HT",
    name: "Haiti",
    regions: [],
  },
  {
    code: "HM",
    name: "Heard Island and McDonald Island",
    regions: [],
  },
  {
    code: "VA",
    name: "Holy See (Vatican City State)",
    regions: [],
  },
  {
    code: "HN",
    name: "Honduras",
    regions: [],
  },
  {
    code: "HK",
    name: "Hong Kong",
    regions: [],
  },
  {
    code: "HU",
    name: "Hungary",
    regions: [],
  },
  {
    code: "IS",
    name: "Iceland",
    regions: [],
  },
  {
    code: "IN",
    name: "India",
    regions: [
      { code: "AN", name: "Andaman and Nicobar Islands" },
      { code: "AP", name: "Andhra Pradesh" },
      { code: "AR", name: "Arunachal Pradesh" },
      { code: "AS", name: "Assam" },
      { code: "BR", name: "Bihar" },
      { code: "CH", name: "Chandigarh" },
      { code: "CT", name: "Chhattisgarh" },
      { code: "DN", name: "Dadra and Nagar Haveli" },
      { code: "DD", name: "Daman and Diu" },
      { code: "DL", name: "Delhi" },
      { code: "GA", name: "Goa" },
      { code: "GJ", name: "Gujarat" },
      { code: "HR", name: "Haryana" },
      { code: "HP", name: "Himachal Pradesh" },
      { code: "JK", name: "Jammu and Kashmir" },
      { code: "JH", name: "Jharkhand" },
      { code: "KA", name: "Karnataka" },
      { code: "KL", name: "Kerala" },
      { code: "LD", name: "Lakshadweep" },
      { code: "MP", name: "Madhya Pradesh" },
      { code: "MH", name: "Maharashtra" },
      { code: "MN", name: "Manipur" },
      { code: "ML", name: "Meghalaya" },
      { code: "MZ", name: "Mizoram" },
      { code: "NL", name: "Nagaland" },
      { code: "OR", name: "Odisha" },
      { code: "PY", name: "Puducherry" },
      { code: "PB", name: "Punjab" },
      { code: "RJ", name: "Rajasthan" },
      { code: "SK", name: "Sikkim" },
      { code: "TN", name: "Tamil Nadu" },
      { code: "TG", name: "Telangana" },
      { code: "TR", name: "Tripura" },
      { code: "UT", name: "Uttarakhand" },
      { code: "UP", name: "Uttar Pradesh" },
      { code: "WB", name: "West Bengal" },
    ],
  },
  {
    code: "ID",
    name: "Indonesia",
    regions: [],
  },
  {
    code: "IR",
    name: "Iran, Islamic Republic of",
    regions: [],
  },
  {
    code: "IQ",
    name: "Iraq",
    regions: [],
  },
  {
    code: "IE",
    name: "Ireland",
    regions: [
      { code: "CW", name: "Carlow" },
      { code: "CN", name: "Cavan" },
      { code: "CE", name: "Clare" },
      { code: "CO", name: "Cork" },
      { code: "DL", name: "Donegal" },
      { code: "D", name: "Dublin" },
      { code: "G", name: "Galway" },
      { code: "KY", name: "Kerry" },
      { code: "KE", name: "Kildare" },
      { code: "KK", name: "Kilkenny" },
      { code: "LS", name: "Laois" },
      { code: "LM", name: "Leitrim" },
      { code: "LK", name: "Limerick" },
      { code: "LD", name: "Longford" },
      { code: "LH", name: "Louth" },
      { code: "MO", name: "Mayo" },
      { code: "MH", name: "Meath" },
      { code: "MN", name: "Monaghan" },
      { code: "OY", name: "Offaly" },
      { code: "RN", name: "Roscommon" },
      { code: "SO", name: "Sligo" },
      { code: "TA", name: "Tipperary" },
      { code: "WD", name: "Waterford" },
      { code: "WH", name: "Westmeath" },
      { code: "WX", name: "Wexford" },
      { code: "WW", name: "Wicklow" },
    ],
  },
  {
    code: "IM",
    name: "Isle of Man",
    regions: [],
  },
  {
    code: "IL",
    name: "Israel",
    regions: [],
  },
  {
    code: "IT",
    name: "Italy",
    regions: [],
  },
  {
    code: "JM",
    name: "Jamaica",
    regions: [],
  },
  {
    code: "JP",
    name: "Japan",
    regions: [
      { code: "10", name: "Gunma" },
      { code: "11", name: "Saitama" },
      { code: "12", name: "Chiba" },
      { code: "13", name: "Tokyo" },
      { code: "14", name: "Kanagawa" },
      { code: "15", name: "Niigata" },
      { code: "16", name: "Toyama" },
      { code: "17", name: "Ishikawa" },
      { code: "18", name: "Fukui" },
      { code: "19", name: "Yamanashi" },
      { code: "20", name: "Nagano" },
      { code: "21", name: "Gifu" },
      { code: "22", name: "Shizuoka" },
      { code: "23", name: "Aichi" },
      { code: "24", name: "Mie" },
      { code: "25", name: "Shiga" },
      { code: "26", name: "Kyoto" },
      { code: "27", name: "Osaka" },
      { code: "28", name: "Hyogo" },
      { code: "29", name: "Nara" },
      { code: "30", name: "Wakayama" },
      { code: "31", name: "Tottori" },
      { code: "32", name: "Shimane" },
      { code: "33", name: "Okayama" },
      { code: "34", name: "Hiroshima" },
      { code: "35", name: "Yamaguchi" },
      { code: "36", name: "Tokushima" },
      { code: "37", name: "Kagawa" },
      { code: "38", name: "Ehime" },
      { code: "39", name: "Kochi" },
      { code: "40", name: "Fukuoka" },
      { code: "41", name: "Saga" },
      { code: "42", name: "Nagasaki" },
      { code: "43", name: "Kumamoto" },
      { code: "44", name: "Oita" },
      { code: "45", name: "Miyazaki" },
      { code: "46", name: "Kagoshima" },
      { code: "47", name: "Okinawa" },
      { code: "05", name: "Akita" },
      { code: "02", name: "Aomori" },
      { code: "07", name: "Fukushima" },
      { code: "01", name: "Hokkaido" },
      { code: "08", name: "Ibaraki" },
      { code: "03", name: "Iwate" },
      { code: "04", name: "Miyagi" },
      { code: "09", name: "Tochigi" },
      { code: "06", name: "Yamagata" },
    ],
  },
  {
    code: "JE",
    name: "Jersey",
    regions: [],
  },
  {
    code: "JO",
    name: "Jordan",
    regions: [],
  },
  {
    code: "KZ",
    name: "Kazakhstan",
    regions: [],
  },
  {
    code: "KE",
    name: "Kenya",
    regions: [],
  },
  {
    code: "KI",
    name: "Kiribati",
    regions: [],
  },
  {
    code: "KP",
    name: "Korea, Democratic People's Republic of",
    regions: [],
  },
  {
    code: "KR",
    name: "Korea, Republic of",
    regions: [],
  },
  {
    code: "KW",
    name: "Kuwait",
    regions: [],
  },
  {
    code: "KG",
    name: "Kyrgyzstan",
    regions: [],
  },
  {
    code: "LA",
    name: "Lao People's Democratic Republic",
    regions: [],
  },
  {
    code: "LV",
    name: "Latvia",
    regions: [],
  },
  {
    code: "LB",
    name: "Lebanon",
    regions: [],
  },
  {
    code: "LS",
    name: "Lesotho",
    regions: [],
  },
  {
    code: "LR",
    name: "Liberia",
    regions: [],
  },
  {
    code: "LY",
    name: "Libya",
    regions: [],
  },
  {
    code: "LI",
    name: "Liechtenstein",
    regions: [],
  },
  {
    code: "LT",
    name: "Lithuania",
    regions: [],
  },
  {
    code: "LU",
    name: "Luxembourg",
    regions: [],
  },
  {
    code: "MO",
    name: "Macau Special Administrative Region of China",
    regions: [],
  },
  {
    code: "MG",
    name: "Madagascar",
    regions: [],
  },
  {
    code: "MW",
    name: "Malawi",
    regions: [],
  },
  {
    code: "MY",
    name: "Malaysia",
    regions: [],
  },
  {
    code: "MV",
    name: "Maldives",
    regions: [],
  },
  {
    code: "ML",
    name: "Mali",
    regions: [],
  },
  {
    code: "MT",
    name: "Malta",
    regions: [],
  },
  {
    code: "MH",
    name: "Marshall Islands",
    regions: [],
  },
  {
    code: "MQ",
    name: "Martinique",
    regions: [],
  },
  {
    code: "MR",
    name: "Mauritania",
    regions: [],
  },
  {
    code: "MU",
    name: "Mauritius",
    regions: [],
  },
  {
    code: "YT",
    name: "Mayotte",
    regions: [],
  },
  {
    code: "MX",
    name: "Mexico",
    regions: [],
  },
  {
    code: "FM",
    name: "Micronesia, Federated States of",
    regions: [],
  },
  {
    code: "MD",
    name: "Moldova, Republic of",
    regions: [],
  },
  {
    code: "MC",
    name: "Monaco",
    regions: [],
  },
  {
    code: "MN",
    name: "Mongolia",
    regions: [],
  },
  {
    code: "ME",
    name: "Montenegro",
    regions: [],
  },
  {
    code: "MS",
    name: "Montserrat",
    regions: [],
  },
  {
    code: "MA",
    name: "Morocco",
    regions: [],
  },
  {
    code: "MZ",
    name: "Mozambique",
    regions: [],
  },
  {
    code: "MM",
    name: "Myanmar",
    regions: [],
  },
  {
    code: "NA",
    name: "Namibia",
    regions: [],
  },
  {
    code: "NR",
    name: "Nauru",
    regions: [],
  },
  {
    code: "NP",
    name: "Nepal",
    regions: [],
  },
  {
    code: "NL",
    name: "Netherlands",
    regions: [],
  },
  {
    code: "NC",
    name: "New Caledonia",
    regions: [],
  },
  {
    code: "NZ",
    name: "New Zealand",
    regions: [],
  },
  {
    code: "NI",
    name: "Nicaragua",
    regions: [],
  },
  {
    code: "NE",
    name: "Niger",
    regions: [],
  },
  {
    code: "NG",
    name: "Nigeria",
    regions: [],
  },
  {
    code: "NU",
    name: "Niue",
    regions: [],
  },
  {
    code: "NF",
    name: "Norfolk Island",
    regions: [],
  },
  {
    code: "MK",
    name: "North Macedonia",
    regions: [],
  },
  {
    code: "MP",
    name: "Northern Mariana Islands",
    regions: [],
  },
  {
    code: "NO",
    name: "Norway",
    regions: [
      { code: "10", name: "Vest-Agder" },
      { code: "11", name: "Rogaland" },
      { code: "12", name: "Hordaland" },
      { code: "14", name: "Sogn og Fjordane" },
      { code: "15", name: "Møre og Romsdal" },
      { code: "16", name: "Sør-Trøndelag" },
      { code: "17", name: "Nord-Trøndelag" },
      { code: "18", name: "Nordland" },
      { code: "19", name: "Troms" },
      { code: "20", name: "Finnmark" },
      { code: "30", name: "Viken" },
      { code: "34", name: "Innlandet" },
      { code: "38", name: "Vestfold og Telemark" },
      { code: "42", name: "Agder" },
      { code: "46", name: "Vestland" },
      { code: "50", name: "Trøndelag" },
      { code: "54", name: "Troms og Finnmark" },
      { code: "01", name: "Østfold" },
      { code: "02", name: "Akershus" },
      { code: "03", name: "Oslo" },
      { code: "04", name: "Hedmark" },
      { code: "05", name: "Oppland" },
      { code: "06", name: "Buskerud" },
      { code: "07", name: "Vestfold" },
      { code: "08", name: "Telemark" },
      { code: "09", name: "Aust-Agder" },
    ],
  },
  {
    code: "OM",
    name: "Oman",
    regions: [],
  },
  {
    code: "PK",
    name: "Pakistan",
    regions: [],
  },
  {
    code: "PW",
    name: "Palau",
    regions: [],
  },
  {
    code: "PS",
    name: "Palestine, State of",
    regions: [],
  },
  {
    code: "PA",
    name: "Panama",
    regions: [],
  },
  {
    code: "PG",
    name: "Papua New Guinea",
    regions: [],
  },
  {
    code: "PY",
    name: "Paraguay",
    regions: [],
  },
  {
    code: "PE",
    name: "Peru",
    regions: [],
  },
  {
    code: "PH",
    name: "Philippines",
    regions: [],
  },
  {
    code: "PN",
    name: "Pitcairn",
    regions: [],
  },
  {
    code: "PL",
    name: "Poland",
    regions: [],
  },
  {
    code: "PT",
    name: "Portugal",
    regions: [],
  },
  {
    code: "PR",
    name: "Puerto Rico",
    regions: [],
  },
  {
    code: "QA",
    name: "Qatar",
    regions: [],
  },
  {
    code: "RE",
    name: "Réunion",
    regions: [],
  },
  {
    code: "RO",
    name: "Romania",
    regions: [],
  },
  {
    code: "RU",
    name: "Russian Federation",
    regions: [],
  },
  {
    code: "RW",
    name: "Rwanda",
    regions: [],
  },
  {
    code: "BL",
    name: "Saint Barthélemy",
    regions: [],
  },
  {
    code: "SH",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    regions: [],
  },
  {
    code: "KN",
    name: "Saint Kitts and Nevis",
    regions: [],
  },
  {
    code: "LC",
    name: "Saint Lucia",
    regions: [],
  },
  {
    code: "MF",
    name: "Saint Martin",
    regions: [],
  },
  {
    code: "PM",
    name: "Saint Pierre and Miquelon",
    regions: [],
  },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    regions: [],
  },
  {
    code: "WS",
    name: "Samoa",
    regions: [],
  },
  {
    code: "SM",
    name: "San Marino",
    regions: [],
  },
  {
    code: "ST",
    name: "Sao Tome and Principe",
    regions: [],
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    regions: [],
  },
  {
    code: "SN",
    name: "Senegal",
    regions: [],
  },
  {
    code: "RS",
    name: "Serbia",
    regions: [],
  },
  {
    code: "SC",
    name: "Seychelles",
    regions: [],
  },
  {
    code: "SL",
    name: "Sierra Leone",
    regions: [],
  },
  {
    code: "SG",
    name: "Singapore",
    regions: [],
  },
  {
    code: "SX",
    name: "Sint Maarten",
    regions: [],
  },
  {
    code: "SK",
    name: "Slovakia",
    regions: [],
  },
  {
    code: "SI",
    name: "Slovenia",
    regions: [],
  },
  {
    code: "SB",
    name: "Solomon Islands",
    regions: [],
  },
  {
    code: "SO",
    name: "Somalia",
    regions: [],
  },
  {
    code: "ZA",
    name: "South Africa",
    regions: [],
  },
  {
    code: "GS",
    name: "South Georgia and the South Sandwich Islands",
    regions: [],
  },
  {
    code: "SS",
    name: "South Sudan",
    regions: [],
  },
  {
    code: "ES",
    name: "Spain",
    regions: [
      { code: "A Coruna", name: "A Coruna" },
      { code: "Alava", name: "Alava" },
      { code: "Albacete", name: "Albacete" },
      { code: "Alicante", name: "Alicante" },
      { code: "Almeria", name: "Almeria" },
      { code: "Asturias", name: "Asturias" },
      { code: "Avila", name: "Avila" },
      { code: "Badajoz", name: "Badajoz" },
      { code: "Baleares", name: "Baleares" },
      { code: "Barcelona", name: "Barcelona" },
      { code: "Burgos", name: "Burgos" },
      { code: "Caceres", name: "Caceres" },
      { code: "Cadiz", name: "Cadiz" },
      { code: "CN", name: "Canarias" },
      { code: "Cantabria", name: "Cantabria" },
      { code: "Castellon", name: "Castellon" },
      { code: "Ceuta", name: "Ceuta" },
      { code: "Ciudad Real", name: "Ciudad Real" },
      { code: "Cordoba", name: "Cordoba" },
      { code: "Cuenca", name: "Cuenca" },
      { code: "Gipuzkoa", name: "Gipuzkoa" },
      { code: "Girona", name: "Girona" },
      { code: "Granada", name: "Granada" },
      { code: "Guadalajara", name: "Guadalajara" },
      { code: "Guipuzcoa", name: "Guipuzcoa" },
      { code: "Huelva", name: "Huelva" },
      { code: "Huesca", name: "Huesca" },
      { code: "Jaen", name: "Jaen" },
      { code: "La Rioja", name: "La Rioja" },
      { code: "Las Palmas", name: "Las Palmas" },
      { code: "Leon", name: "Leon" },
      { code: "Lleida", name: "Lleida" },
      { code: "Lugo", name: "Lugo" },
      { code: "Madrid", name: "Madrid" },
      { code: "Malaga", name: "Malaga" },
      { code: "Melilla", name: "Melilla" },
      { code: "Murcia", name: "Murcia" },
      { code: "Navarra", name: "Navarra" },
      { code: "Ourense", name: "Ourense" },
      { code: "Palencia", name: "Palencia" },
      { code: "Pontevedra", name: "Pontevedra" },
      { code: "Salamanca", name: "Salamanca" },
      { code: "Santa Cruz de Tenerife", name: "Santa Cruz de Tenerife" },
      { code: "Segovia", name: "Segovia" },
      { code: "Sevilla", name: "Sevilla" },
      { code: "Soria", name: "Soria" },
      { code: "Tarragona", name: "Tarragona" },
      { code: "Teruel", name: "Teruel" },
      { code: "Toledo", name: "Toledo" },
      { code: "Valencia", name: "Valencia" },
      { code: "Valladolid", name: "Valladolid" },
      { code: "Vizcaya", name: "Biscay" },
      { code: "Zamora", name: "Zamora" },
      { code: "Zaragoza", name: "Zaragoza" },
    ],
  },
  {
    code: "LK",
    name: "Sri Lanka",
    regions: [],
  },
  {
    code: "SD",
    name: "Sudan",
    regions: [],
  },
  {
    code: "SR",
    name: "Suriname",
    regions: [],
  },
  {
    code: "SJ",
    name: "Svalbard and Jan Mayen",
    regions: [],
  },
  {
    code: "SE",
    name: "Sweden",
    regions: [],
  },
  {
    code: "CH",
    name: "Switzerland",
    regions: [
      { code: "AG", name: "Aargau" },
      { code: "AR", name: "Appenzell Ausserrhoden" },
      { code: "AI", name: "Appenzell Innerrhoden" },
      { code: "BL", name: "Basel-Landschaft" },
      { code: "BS", name: "Basel-Stadt" },
      { code: "BE", name: "Bern" },
      { code: "FR", name: "Freiburg" },
      { code: "GE", name: "Genf" },
      { code: "GL", name: "Glarus" },
      { code: "GR", name: "Graubuenden" },
      { code: "JU", name: "Jura" },
      { code: "LU", name: "Luzern" },
      { code: "NE", name: "Neuenburg" },
      { code: "NW", name: "Nidwalden" },
      { code: "OW", name: "Obwalden" },
      { code: "SH", name: "Schaffhausen" },
      { code: "SZ", name: "Schwyz" },
      { code: "SO", name: "Solothurn" },
      { code: "SG", name: "St. Gallen" },
      { code: "TI", name: "Tessin" },
      { code: "TG", name: "Thurgau" },
      { code: "UR", name: "Uri" },
      { code: "VS", name: "Valais" },
      { code: "VD", name: "Vaud" },
      { code: "ZH", name: "Zurich" },
      { code: "ZG", name: "Zug" },
    ],
  },
  {
    code: "SY",
    name: "Syrian Arab Republic",
    regions: [],
  },
  {
    code: "TW",
    name: "Taiwan",
    regions: [],
  },
  {
    code: "TJ",
    name: "Tajikistan",
    regions: [],
  },
  {
    code: "TZ",
    name: "Tanzania, United Republic of",
    regions: [],
  },
  {
    code: "TH",
    name: "Thailand",
    regions: [],
  },
  {
    code: "TL",
    name: "Timor-Leste",
    regions: [],
  },
  {
    code: "TG",
    name: "Togo",
    regions: [],
  },
  {
    code: "TK",
    name: "Tokelau",
    regions: [],
  },
  {
    code: "TO",
    name: "Tonga",
    regions: [],
  },
  {
    code: "TT",
    name: "Trinidad and Tobago",
    regions: [],
  },
  {
    code: "TN",
    name: "Tunisia",
    regions: [],
  },
  {
    code: "TR",
    name: "Turkey",
    regions: [],
  },
  {
    code: "TM",
    name: "Turkmenistan",
    regions: [],
  },
  {
    code: "TC",
    name: "Turks and Caicos Islands",
    regions: [],
  },
  {
    code: "TV",
    name: "Tuvalu",
    regions: [],
  },
  {
    code: "UG",
    name: "Uganda",
    regions: [],
  },
  {
    code: "UA",
    name: "Ukraine",
    regions: [],
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    regions: [],
  },
  {
    code: "GB",
    name: "United Kingdom",
    regions: [],
  },
  {
    code: "US",
    name: "United States",
    regions: [
      { code: "AL", name: "Alabama" },
      { code: "AK", name: "Alaska" },
      { code: "AS", name: "American Samoa" },
      { code: "AZ", name: "Arizona" },
      { code: "AR", name: "Arkansas" },
      { code: "AF", name: "Armed Forces Africa" },
      { code: "AA", name: "Armed Forces Americas" },
      { code: "AC", name: "Armed Forces Canada" },
      { code: "AE", name: "Armed Forces Europe" },
      { code: "AM", name: "Armed Forces Middle East" },
      { code: "AP", name: "Armed Forces Pacific" },
      { code: "CA", name: "California" },
      { code: "CO", name: "Colorado" },
      { code: "CT", name: "Connecticut" },
      { code: "DE", name: "Delaware" },
      { code: "DC", name: "Washington DC" },
      { code: "FM", name: "Federated States Of Micronesia" },
      { code: "FL", name: "Florida" },
      { code: "GA", name: "Georgia" },
      { code: "GU", name: "Guam" },
      { code: "HI", name: "Hawaii" },
      { code: "ID", name: "Idaho" },
      { code: "IL", name: "Illinois" },
      { code: "IN", name: "Indiana" },
      { code: "IA", name: "Iowa" },
      { code: "KS", name: "Kansas" },
      { code: "KY", name: "Kentucky" },
      { code: "LA", name: "Louisiana" },
      { code: "ME", name: "Maine" },
      { code: "MH", name: "Marshall Islands" },
      { code: "MD", name: "Maryland" },
      { code: "MA", name: "Massachusetts" },
      { code: "MI", name: "Michigan" },
      { code: "MN", name: "Minnesota" },
      { code: "MS", name: "Mississippi" },
      { code: "MO", name: "Missouri" },
      { code: "MT", name: "Montana" },
      { code: "NE", name: "Nebraska" },
      { code: "NV", name: "Nevada" },
      { code: "NH", name: "New Hampshire" },
      { code: "NJ", name: "New Jersey" },
      { code: "NM", name: "New Mexico" },
      { code: "NY", name: "New York" },
      { code: "NC", name: "North Carolina" },
      { code: "ND", name: "North Dakota" },
      { code: "MP", name: "Northern Mariana Islands" },
      { code: "OH", name: "Ohio" },
      { code: "OK", name: "Oklahoma" },
      { code: "OR", name: "Oregon" },
      { code: "PA", name: "Pennsylvania" },
      { code: "PR", name: "Puerto Rico" },
      { code: "RI", name: "Rhode Island" },
      { code: "SC", name: "South Carolina" },
      { code: "SD", name: "South Dakota" },
      { code: "TN", name: "Tennessee" },
      { code: "TX", name: "Texas" },
      { code: "UT", name: "Utah" },
      { code: "VT", name: "Vermont" },
      { code: "VI", name: "Virgin Islands" },
      { code: "VA", name: "Virginia" },
      { code: "WA", name: "Washington" },
      { code: "WV", name: "West Virginia" },
      { code: "WI", name: "Wisconsin" },
      { code: "WY", name: "Wyoming" },
    ],
  },
  {
    code: "UM",
    name: "United States Minor Outlying Islands",
    regions: [],
  },
  {
    code: "UY",
    name: "Uruguay",
    regions: [],
  },
  {
    code: "UZ",
    name: "Uzbekistan",
    regions: [],
  },
  {
    code: "VU",
    name: "Vanuatu",
    regions: [],
  },
  {
    code: "VE",
    name: "Venezuela",
    regions: [],
  },
  {
    code: "VN",
    name: "Vietnam",
    regions: [],
  },
  {
    code: "VG",
    name: "Virgin Islands, British",
    regions: [],
  },
  {
    code: "VI",
    name: "Virgin Islands, U.S.",
    regions: [],
  },
  {
    code: "WF",
    name: "Wallis and Futuna Islands",
    regions: [],
  },
  {
    code: "EH",
    name: "Western Sahara",
    regions: [],
  },
  {
    code: "YE",
    name: "Yemen",
    regions: [],
  },
  {
    code: "ZM",
    name: "Zambia",
    regions: [],
  },
  {
    code: "ZW",
    name: "Zimbabwe",
    regions: [],
  },
];
