name: S3 CDN upload

on:
  push:
    tags:
      - '*'
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Foxy/foxy-elements
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run prepack
      - uses: Foxy/foxy-github-action-s3cdn@main
        with:
          package-name: elements # optional: Default is repo name.
        env:
          AWS_S3_CDN_BUCKET_NAME: ${{ secrets.AWS_S3_CDN_BUCKET_NAME }}
          AWS_S3_CDN_KEY_ID: ${{ secrets.AWS_S3_CDN_KEY_ID }}
          AWS_S3_CDN_KEY_SECRET: ${{ secrets.AWS_S3_CDN_KEY_SECRET }}
          SOURCE_DIR: 'dist/cdn' # optional: defaults to `dist` directory
