import type { NativeIntegrationForm } from './NativeIntegrationForm';
import type { Renderer } from '../../../mixins/configurable';
import type { Resource } from '@foxy.io/sdk/core';
import type { Rels } from '@foxy.io/sdk/backend';

export type Data = Resource<Rels.NativeIntegration>;

export type Templates = {
  'timestamps:before'?: Renderer<NativeIntegrationForm>;
  'timestamps:after'?: Renderer<NativeIntegrationForm>;
  'delete:before'?: Renderer<NativeIntegrationForm>;
  'delete:after'?: Renderer<NativeIntegrationForm>;
  'create:before'?: Renderer<NativeIntegrationForm>;
  'create:after'?: Renderer<NativeIntegrationForm>;
  'provider:before'?: Renderer<NativeIntegrationForm>;
  'provider:after'?: Renderer<NativeIntegrationForm>;
  'avalara-service-url:before'?: Renderer<NativeIntegrationForm>;
  'avalara-service-url:after'?: Renderer<NativeIntegrationForm>;
  'avalara-id:before'?: Renderer<NativeIntegrationForm>;
  'avalara-id:after'?: Renderer<NativeIntegrationForm>;
  'avalara-key:before'?: Renderer<NativeIntegrationForm>;
  'avalara-key:after'?: Renderer<NativeIntegrationForm>;
  'avalara-company-code:before'?: Renderer<NativeIntegrationForm>;
  'avalara-company-code:after'?: Renderer<NativeIntegrationForm>;
  'avalara-options:before'?: Renderer<NativeIntegrationForm>;
  'avalara-options:after'?: Renderer<NativeIntegrationForm>;
  'avalara-address-validation-countries:before'?: Renderer<NativeIntegrationForm>;
  'avalara-address-validation-countries:after'?: Renderer<NativeIntegrationForm>;
  'avalara-category-to-product-tax-code-mappings:before'?: Renderer<NativeIntegrationForm>;
  'avalara-category-to-product-tax-code-mappings:after'?: Renderer<NativeIntegrationForm>;
  'taxjar-api-token:before'?: Renderer<NativeIntegrationForm>;
  'taxjar-api-token:after'?: Renderer<NativeIntegrationForm>;
  'taxjar-category-to-product-tax-code-mappings:before'?: Renderer<NativeIntegrationForm>;
  'taxjar-category-to-product-tax-code-mappings:after'?: Renderer<NativeIntegrationForm>;
  'taxjar-options:before'?: Renderer<NativeIntegrationForm>;
  'taxjar-options:after'?: Renderer<NativeIntegrationForm>;
  'onesource-service-url:before'?: Renderer<NativeIntegrationForm>;
  'onesource-service-url:after'?: Renderer<NativeIntegrationForm>;
  'onesource-external-company-id:before'?: Renderer<NativeIntegrationForm>;
  'onesource-external-company-id:after'?: Renderer<NativeIntegrationForm>;
  'onesource-calling-system-number:before'?: Renderer<NativeIntegrationForm>;
  'onesource-calling-system-number:after'?: Renderer<NativeIntegrationForm>;
  'onesource-from-city:before'?: Renderer<NativeIntegrationForm>;
  'onesource-from-city:after'?: Renderer<NativeIntegrationForm>;
  'onesource-host-system:before'?: Renderer<NativeIntegrationForm>;
  'onesource-host-system:after'?: Renderer<NativeIntegrationForm>;
  'onesource-company-role:before'?: Renderer<NativeIntegrationForm>;
  'onesource-company-role:after'?: Renderer<NativeIntegrationForm>;
  'onesource-part-number-product-option:before'?: Renderer<NativeIntegrationForm>;
  'onesource-part-number-product-option:after'?: Renderer<NativeIntegrationForm>;
  'onesource-product-order-priority:before'?: Renderer<NativeIntegrationForm>;
  'onesource-product-order-priority:after'?: Renderer<NativeIntegrationForm>;
  'onesource-audit-settings:before'?: Renderer<NativeIntegrationForm>;
  'onesource-audit-settings:after'?: Renderer<NativeIntegrationForm>;
  'webhook-service:before'?: Renderer<NativeIntegrationForm>;
  'webhook-service:after'?: Renderer<NativeIntegrationForm>;
  'webhook-json-title:before'?: Renderer<NativeIntegrationForm>;
  'webhook-json-title:after'?: Renderer<NativeIntegrationForm>;
  'webhook-json-encryption-key:before'?: Renderer<NativeIntegrationForm>;
  'webhook-json-encryption-key:after'?: Renderer<NativeIntegrationForm>;
  'webhook-json-url:before'?: Renderer<NativeIntegrationForm>;
  'webhook-json-url:after'?: Renderer<NativeIntegrationForm>;
  'webhook-json-events:before'?: Renderer<NativeIntegrationForm>;
  'webhook-json-events:after'?: Renderer<NativeIntegrationForm>;
  'webhook-legacy-xml-title:before'?: Renderer<NativeIntegrationForm>;
  'webhook-legacy-xml-title:after'?: Renderer<NativeIntegrationForm>;
  'webhook-legacy-xml-url:before'?: Renderer<NativeIntegrationForm>;
  'webhook-legacy-xml-url:after'?: Renderer<NativeIntegrationForm>;
  'webflow-site-id:before'?: Renderer<NativeIntegrationForm>;
  'webflow-site-id:after'?: Renderer<NativeIntegrationForm>;
  'webflow-site-name:before'?: Renderer<NativeIntegrationForm>;
  'webflow-site-name:after'?: Renderer<NativeIntegrationForm>;
  'webflow-collection-id:before'?: Renderer<NativeIntegrationForm>;
  'webflow-collection-id:after'?: Renderer<NativeIntegrationForm>;
  'webflow-collection-name:before'?: Renderer<NativeIntegrationForm>;
  'webflow-collection-name:after'?: Renderer<NativeIntegrationForm>;
  'webflow-sku-field-id:before'?: Renderer<NativeIntegrationForm>;
  'webflow-sku-field-id:after'?: Renderer<NativeIntegrationForm>;
  'webflow-sku-field-name:before'?: Renderer<NativeIntegrationForm>;
  'webflow-sku-field-name:after'?: Renderer<NativeIntegrationForm>;
  'webflow-inventory-field-id:before'?: Renderer<NativeIntegrationForm>;
  'webflow-inventory-field-id:after'?: Renderer<NativeIntegrationForm>;
  'webflow-inventory-field-name:before'?: Renderer<NativeIntegrationForm>;
  'webflow-inventory-field-name:after'?: Renderer<NativeIntegrationForm>;
  'webflow-auth:before'?: Renderer<NativeIntegrationForm>;
  'webflow-auth:after'?: Renderer<NativeIntegrationForm>;
  'zapier-event:before'?: Renderer<NativeIntegrationForm>;
  'zapier-event:after'?: Renderer<NativeIntegrationForm>;
  'zapier-url:before'?: Renderer<NativeIntegrationForm>;
  'zapier-url:after'?: Renderer<NativeIntegrationForm>;
};
